def register_tools():
    return [
        {
            "name": "Random File Picker",
            "category": "Miscellaneous",
            "description": "Random File Picker: random file picker as structured JSON output.",
            "handler": "random_picker.run",
            "cli_command": "random-file",
            "dependencies": [],
        },
        {
            "name": "File Age Calculator",
            "category": "Miscellaneous",
            "description": "File Age Calculator: file age calculator as structured JSON output.",
            "handler": "age_calc.run",
            "cli_command": "file-age",
            "dependencies": [],
        },
        {
            "name": "Path Length Checker",
            "category": "Miscellaneous",
            "description": "Path Length Checker: path length checker as structured JSON output.",
            "handler": "path_length.run",
            "cli_command": "path-length",
            "dependencies": [],
        },
        {
            "name": "Hash Identifier",
            "category": "Miscellaneous",
            "description": "Identify likely hash algorithm from a hash string; optionally verify against plaintext.",
            "handler": "hash_identifier.run",
            "cli_command": "hash-identify",
            "dependencies": [],
        },
        {
            "name": "Password Entropy Calculator",
            "category": "Miscellaneous",
            "description": "Estimate password entropy/strength, or generate strong random passwords.",
            "handler": "entropy_calculator.run",
            "cli_command": "password-entropy",
            "dependencies": [],
        },
        {
            "name": "Base64 Codec",
            "category": "Miscellaneous",
            "description": "Strict Base64 encode/decode with URL-safe and no-padding modes.",
            "handler": "base64_codec.run",
            "cli_command": "b64-codec",
            "dependencies": [],
        },
        {
            "name": "JSON Schema Explorer",
            "category": "Miscellaneous",
            "description": "Print a leaf-path schema of a JSON document (diffing lives in dev_tools: json-diff).",
            "handler": "json_diff.run",
            "cli_command": "json-schema",
            "dependencies": [],
        },
        {
            "name": "CSV Query",
            "category": "Miscellaneous",
            "description": "Filter, project and aggregate CSV rows with column stats; no external tools required.",
            "handler": "csv_query.run",
            "cli_command": "csv-query",
            "dependencies": [],
        },
        {
            "name": "Text Diff",
            "category": "Miscellaneous",
            "description": "Unified/context line diff between two text files via difflib, with change summary mode.",
            "handler": "text_diff.run",
            "cli_command": "text-diff",
            "dependencies": [],
        },
        {
            "name": "IP Subnet Calculator",
            "category": "Miscellaneous",
            "description": "IPv4 CIDR/netmask math: network, broadcast, wildcard, host range and count.",
            "handler": "ipcalc.run",
            "cli_command": "ip-calc",
            "dependencies": [],
        },
        {
            "name": "INI Toolkit",
            "category": "Miscellaneous",
            "description": "Read, query, update and JSON-export INI configuration files with configparser.",
            "handler": "ini_reader.run",
            "cli_command": "ini-tool",
            "dependencies": [],
        },
        {
            "name": "UUID Toolkit",
            "category": "Miscellaneous",
            "description": "Generate v1/v3/v4/v5/nil/max UUIDs in bulk and validate any RFC 4122 string.",
            "handler": "uuid_gen.run",
            "cli_command": "uuid-tool",
            "dependencies": [],
        },
        {
            "name": "Directory Tree Viewer",
            "category": "Miscellaneous",
            "description": "ASCII directory tree with per-entry sizes, depth limits and directories-only mode.",
            "handler": "tree_view.run",
            "cli_command": "tree-print",
            "dependencies": [],
        },
        {
            "name": "Byte Unit Converter",
            "category": "Miscellaneous",
            "description": "Convert storage amounts across decimal (KB/MB) and binary (KiB/MiB) byte units.",
            "handler": "unit_bytes.run",
            "cli_command": "bytes-units",
            "dependencies": [],
        },
        {
            "name": "Random File Generator",
            "category": "Miscellaneous",
            "description": "Create cryptographically-random test files of any size for benchmarking other tools.",
            "handler": "rand_file.run",
            "cli_command": "rand-file",
            "dependencies": [],
        },
    ]
