def register_tools():
    return [
        {
            "name": "Random File Picker",
            "category": "Miscellaneous",
            "description": "Random File Picker: random file picker as structured JSON output.",
            "handler": "random_picker.run",
            "cli_command": "random-file",
            "dependencies": [],
        },
        {
            "name": "File Age Calculator",
            "category": "Miscellaneous",
            "description": "File Age Calculator: file age calculator as structured JSON output.",
            "handler": "age_calc.run",
            "cli_command": "file-age",
            "dependencies": [],
        },
        {
            "name": "Path Length Checker",
            "category": "Miscellaneous",
            "description": "Path Length Checker: path length checker as structured JSON output.",
            "handler": "path_length.run",
            "cli_command": "path-length",
            "dependencies": [],
        },
        {
            "name": "Hash Identifier",
            "category": "Miscellaneous",
            "description": "Identify likely hash algorithm from a hash string; optionally verify against plaintext.",
            "handler": "hash_identifier.run",
            "cli_command": "hash-identify",
            "dependencies": [],
        },
        {
            "name": "Password Entropy Calculator",
            "category": "Miscellaneous",
            "description": "Estimate password entropy/strength, or generate strong random passwords.",
            "handler": "entropy_calculator.run",
            "cli_command": "password-entropy",
            "dependencies": [],
        },
        {
            "name": "Base64 Codec",
            "category": "Miscellaneous",
            "description": "Strict Base64 encode/decode with URL-safe and no-padding modes.",
            "handler": "base64_codec.run",
            "cli_command": "b64-codec",
            "dependencies": [],
        },
        {
            "name": "JSON Schema Explorer",
            "category": "Miscellaneous",
            "description": "Print a leaf-path schema of a JSON document (diffing lives in dev_tools: json-diff).",
            "handler": "json_diff.run",
            "cli_command": "json-schema",
            "dependencies": [],
        },
    ]
