"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Image Batch Inventory",
            "category": "Batch Imaging",
            "description": "Enumerate an inventory of image batch inventory.",
            "handler": "operations.image_batch_inventory",
            "cli_command": "image-batch-inventory",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Dimensions",
            "category": "Batch Imaging",
            "description": "Image Batch Dimensions: image batch dimensions as structured JSON output.",
            "handler": "operations.image_batch_dimensions",
            "cli_command": "image-batch-dimensions",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Extension Convert",
            "category": "Batch Imaging",
            "description": "Image Batch Extension Convert: image batch extension convert as structured JSON output.",
            "handler": "operations.image_batch_extension_convert",
            "cli_command": "image-batch-extension-convert",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Resize Plan",
            "category": "Batch Imaging",
            "description": "Image Batch Resize Plan: image batch resize plan as structured JSON output.",
            "handler": "operations.image_batch_resize_plan",
            "cli_command": "image-batch-resize-plan",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Rename Plan",
            "category": "Batch Imaging",
            "description": "Image Batch Rename Plan: image batch rename plan as structured JSON output.",
            "handler": "operations.image_batch_rename_plan",
            "cli_command": "image-batch-rename-plan",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Hash",
            "category": "Batch Imaging",
            "description": "Image Batch Hash: image batch hash as structured JSON output.",
            "handler": "operations.image_batch_hash",
            "cli_command": "image-batch-hash",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Duplicate Report",
            "category": "Batch Imaging",
            "description": "Compile a readable image batch duplicate report report.",
            "handler": "operations.image_batch_duplicate_report",
            "cli_command": "image-batch-duplicate-report",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Contact Sheet",
            "category": "Batch Imaging",
            "description": "Image Batch Contact Sheet: image batch contact sheet as structured JSON output.",
            "handler": "operations.image_batch_contact_sheet",
            "cli_command": "image-batch-contact-sheet",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Metadata Report",
            "category": "Batch Imaging",
            "description": "Compile a readable image batch metadata report report.",
            "handler": "operations.image_batch_metadata_report",
            "cli_command": "image-batch-metadata-report",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Orientation Report",
            "category": "Batch Imaging",
            "description": "Compile a readable image batch orientation report report.",
            "handler": "operations.image_batch_orientation_report",
            "cli_command": "image-batch-orientation-report",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Folder Summary",
            "category": "Batch Imaging",
            "description": "Summarize image batch folder summary at a glance.",
            "handler": "operations.image_batch_folder_summary",
            "cli_command": "image-batch-folder-summary",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch CSV Export",
            "category": "Batch Imaging",
            "description": "Export image batch csv data to a file.",
            "handler": "operations.image_batch_csv_export",
            "cli_command": "image-batch-csv-export",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch JSON Export",
            "category": "Batch Imaging",
            "description": "Export image batch json data to a file.",
            "handler": "operations.image_batch_json_export",
            "cli_command": "image-batch-json-export",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Cleanup Plan",
            "category": "Batch Imaging",
            "description": "Image Batch Cleanup Plan: image batch cleanup plan as structured JSON output.",
            "handler": "operations.image_batch_cleanup_plan",
            "cli_command": "image-batch-cleanup-plan",
            "dependencies": ["Pillow"],
        },
    ]
