"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Process List",
            "category": "Process Tools",
            "description": "Process List: process-list operation.",
            "handler": "operations.process_list",
            "cli_command": "process-list",
            "dependencies": [],
        },
        {
            "name": "Process Details",
            "category": "Process Tools",
            "description": "Process Details: process-details operation.",
            "handler": "operations.process_details",
            "cli_command": "process-details",
            "dependencies": [],
        },
        {
            "name": "Process Search",
            "category": "Process Tools",
            "description": "Process Search: process-search operation.",
            "handler": "operations.process_search",
            "cli_command": "process-search",
            "dependencies": [],
        },
        {
            "name": "Process Tree",
            "category": "Process Tools",
            "description": "Process Tree: process-tree operation.",
            "handler": "operations.process_tree",
            "cli_command": "process-tree",
            "dependencies": [],
        },
        {
            "name": "Process CPU Snapshot",
            "category": "Process Tools",
            "description": "Process CPU Snapshot: process-cpu-snapshot operation.",
            "handler": "operations.process_cpu_snapshot",
            "cli_command": "process-cpu-snapshot",
            "dependencies": [],
        },
        {
            "name": "Process Memory Snapshot",
            "category": "Process Tools",
            "description": "Process Memory Snapshot: process-memory-snapshot operation.",
            "handler": "operations.process_memory_snapshot",
            "cli_command": "process-memory-snapshot",
            "dependencies": [],
        },
        {
            "name": "Process Handle Summary",
            "category": "Process Tools",
            "description": "Process Handle Summary: process-handle-summary operation.",
            "handler": "operations.process_handle_summary",
            "cli_command": "process-handle-summary",
            "dependencies": [],
        },
        {
            "name": "Process Start Time",
            "category": "Process Tools",
            "description": "Process Start Time: process-start-time operation.",
            "handler": "operations.process_start_time",
            "cli_command": "process-start-time",
            "dependencies": [],
        },
        {
            "name": "Process Environment Summary",
            "category": "Process Tools",
            "description": "Process Environment Summary: process-environment-summary operation.",
            "handler": "operations.process_environment_summary",
            "cli_command": "process-environment-summary",
            "dependencies": [],
        },
        {
            "name": "Process Path Resolver",
            "category": "Process Tools",
            "description": "Process Path Resolver: process-path-resolver operation.",
            "handler": "operations.process_path_resolver",
            "cli_command": "process-path-resolver",
            "dependencies": [],
        },
        {
            "name": "Process Priority Reader",
            "category": "Process Tools",
            "description": "Process Priority Reader: process-priority-reader operation.",
            "handler": "operations.process_priority_reader",
            "cli_command": "process-priority-reader",
            "dependencies": [],
        },
        {
            "name": "Process Priority Setter",
            "category": "Process Tools",
            "description": "Process Priority Setter: process-priority-setter operation.",
            "handler": "operations.process_priority_setter",
            "cli_command": "process-priority-setter",
            "dependencies": [],
        },
        {
            "name": "Process Affinity Reader",
            "category": "Process Tools",
            "description": "Process Affinity Reader: process-affinity-reader operation.",
            "handler": "operations.process_affinity_reader",
            "cli_command": "process-affinity-reader",
            "dependencies": [],
        },
        {
            "name": "Process Affinity Setter",
            "category": "Process Tools",
            "description": "Process Affinity Setter: process-affinity-setter operation.",
            "handler": "operations.process_affinity_setter",
            "cli_command": "process-affinity-setter",
            "dependencies": [],
        },
        {
            "name": "Process Terminate",
            "category": "Process Tools",
            "description": "Process Terminate: process-terminate operation.",
            "handler": "operations.process_terminate",
            "cli_command": "process-terminate",
            "dependencies": [],
        },
        {
            "name": "Process Wait",
            "category": "Process Tools",
            "description": "Process Wait: process-wait operation.",
            "handler": "operations.process_wait",
            "cli_command": "process-wait",
            "dependencies": [],
        },
    ]
