"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Startup Folder Viewer",
            "category": "Startup & Automation",
            "description": "Startup Folder Viewer. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.startup_folder_viewer",
            "cli_command": "startup-folder-viewer",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Startup Entry Inventory",
            "category": "Startup & Automation",
            "description": "Startup Entry Inventory. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.startup_entry_inventory",
            "cli_command": "startup-entry-inventory",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Startup Folder Cleaner",
            "category": "Startup & Automation",
            "description": "Startup Folder Cleaner. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.startup_folder_cleaner",
            "cli_command": "startup-folder-cleaner",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task List",
            "category": "Startup & Automation",
            "description": "Scheduled Task List. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.scheduled_task_list",
            "cli_command": "scheduled-task-list",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Details",
            "category": "Startup & Automation",
            "description": "Scheduled Task Details. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.scheduled_task_details",
            "cli_command": "scheduled-task-details",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Run",
            "category": "Startup & Automation",
            "description": "Scheduled Task Run. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.scheduled_task_run",
            "cli_command": "scheduled-task-run",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Disable",
            "category": "Startup & Automation",
            "description": "Scheduled Task Disable. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.scheduled_task_disable",
            "cli_command": "scheduled-task-disable",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Enable",
            "category": "Startup & Automation",
            "description": "Scheduled Task Enable. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.scheduled_task_enable",
            "cli_command": "scheduled-task-enable",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Task XML Export",
            "category": "Startup & Automation",
            "description": "Task XML Export. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.task_xml_export",
            "cli_command": "task-xml-export",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Task Trigger Guide",
            "category": "Startup & Automation",
            "description": "Task Trigger Guide. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.task_trigger_guide",
            "cli_command": "task-trigger-guide",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Folder Watch Snapshot",
            "category": "Startup & Automation",
            "description": "Folder Watch Snapshot. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.folder_watch_snapshot",
            "cli_command": "folder-watch-snapshot",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Automation Manifest",
            "category": "Startup & Automation",
            "description": "Automation Manifest. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.automation_manifest",
            "cli_command": "automation-manifest",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Startup Report",
            "category": "Startup & Automation",
            "description": "Startup Report. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.startup_report",
            "cli_command": "startup-report",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Logon Task Report",
            "category": "Startup & Automation",
            "description": "Logon Task Report. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.logon_task_report",
            "cli_command": "logon-task-report",
            "dependencies": ["schtasks"],
        },
    ]
