"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Startup Folder Viewer",
            "category": "Startup & Automation",
            "description": "Startup Folder Viewer: performs the startup folder viewer action with structured, human-readable output.",
            "handler": "operations.startup_folder_viewer",
            "cli_command": "startup-folder-viewer",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Startup Entry Inventory",
            "category": "Startup & Automation",
            "description": "Startup Entry Inventory: performs the startup entry inventory action with structured, human-readable output.",
            "handler": "operations.startup_entry_inventory",
            "cli_command": "startup-entry-inventory",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Startup Folder Cleaner",
            "category": "Startup & Automation",
            "description": "Startup Folder Cleaner: performs the startup folder cleaner action with structured, human-readable output.",
            "handler": "operations.startup_folder_cleaner",
            "cli_command": "startup-folder-cleaner",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task List",
            "category": "Startup & Automation",
            "description": "Scheduled Task List: performs the scheduled task list action with structured, human-readable output.",
            "handler": "operations.scheduled_task_list",
            "cli_command": "scheduled-task-list",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Details",
            "category": "Startup & Automation",
            "description": "Scheduled Task Details: performs the scheduled task details action with structured, human-readable output.",
            "handler": "operations.scheduled_task_details",
            "cli_command": "scheduled-task-details",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Run",
            "category": "Startup & Automation",
            "description": "Scheduled Task Run: performs the scheduled task run action with structured, human-readable output.",
            "handler": "operations.scheduled_task_run",
            "cli_command": "scheduled-task-run",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Disable",
            "category": "Startup & Automation",
            "description": "Scheduled Task Disable: performs the scheduled task disable action with structured, human-readable output.",
            "handler": "operations.scheduled_task_disable",
            "cli_command": "scheduled-task-disable",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Scheduled Task Enable",
            "category": "Startup & Automation",
            "description": "Scheduled Task Enable: performs the scheduled task enable action with structured, human-readable output.",
            "handler": "operations.scheduled_task_enable",
            "cli_command": "scheduled-task-enable",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Task XML Export",
            "category": "Startup & Automation",
            "description": "Task XML Export: performs the task xml export action with structured, human-readable output.",
            "handler": "operations.task_xml_export",
            "cli_command": "task-xml-export",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Task Trigger Guide",
            "category": "Startup & Automation",
            "description": "Task Trigger Guide: performs the task trigger guide action with structured, human-readable output.",
            "handler": "operations.task_trigger_guide",
            "cli_command": "task-trigger-guide",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Folder Watch Snapshot",
            "category": "Startup & Automation",
            "description": "Folder Watch Snapshot: performs the folder watch snapshot action with structured, human-readable output.",
            "handler": "operations.folder_watch_snapshot",
            "cli_command": "folder-watch-snapshot",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Automation Manifest",
            "category": "Startup & Automation",
            "description": "Automation Manifest: performs the automation manifest action with structured, human-readable output.",
            "handler": "operations.automation_manifest",
            "cli_command": "automation-manifest",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Startup Report",
            "category": "Startup & Automation",
            "description": "Startup Report: performs the startup report action with structured, human-readable output.",
            "handler": "operations.startup_report",
            "cli_command": "startup-report",
            "dependencies": ["schtasks"],
        },
        {
            "name": "Logon Task Report",
            "category": "Startup & Automation",
            "description": "Logon Task Report: performs the logon task report action with structured, human-readable output.",
            "handler": "operations.logon_task_report",
            "cli_command": "logon-task-report",
            "dependencies": ["schtasks"],
        },
    ]
