"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "PDF Metadata Reader",
            "category": "PDF Tools",
            "description": "Read and print pdf metadata.",
            "handler": "operations.pdf_metadata_reader",
            "cli_command": "pdf-metadata-reader",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Metadata Cleaner",
            "category": "PDF Tools",
            "description": "Clean up pdf metadata.",
            "handler": "operations.pdf_metadata_cleaner",
            "cli_command": "pdf-metadata-cleaner",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Page Counter",
            "category": "PDF Tools",
            "description": "Count occurrences within pdf page.",
            "handler": "operations.pdf_page_counter",
            "cli_command": "pdf-page-counter",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Text Search",
            "category": "PDF Tools",
            "description": "Search pdf text targets for matches.",
            "handler": "operations.pdf_text_search",
            "cli_command": "pdf-text-search",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Page Extractor",
            "category": "PDF Tools",
            "description": "Extract data from pdf page.",
            "handler": "operations.pdf_page_extractor",
            "cli_command": "pdf-page-extractor",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Merge",
            "category": "PDF Tools",
            "description": "PDF Merge: pdf merge as structured JSON output.",
            "handler": "operations.pdf_merge",
            "cli_command": "pdf-merge",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Split",
            "category": "PDF Tools",
            "description": "PDF Split: pdf split as structured JSON output.",
            "handler": "operations.pdf_split",
            "cli_command": "pdf-split",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Rotate",
            "category": "PDF Tools",
            "description": "Rotate pdf logs or content.",
            "handler": "operations.pdf_rotate",
            "cli_command": "pdf-rotate",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Compress",
            "category": "PDF Tools",
            "description": "PDF Compress: pdf compress as structured JSON output.",
            "handler": "operations.pdf_compress",
            "cli_command": "pdf-compress",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Watermark",
            "category": "PDF Tools",
            "description": "PDF Watermark: pdf watermark as structured JSON output.",
            "handler": "operations.pdf_watermark",
            "cli_command": "pdf-watermark",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Image Extractor",
            "category": "PDF Tools",
            "description": "Extract data from pdf image.",
            "handler": "operations.pdf_image_extractor",
            "cli_command": "pdf-image-extractor",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
        {
            "name": "PDF Attachment Inspector",
            "category": "PDF Tools",
            "description": "Inspect pdf attachment and report internals.",
            "handler": "operations.pdf_attachment_inspector",
            "cli_command": "pdf-attachment-inspector",
            "dependencies": ["pdftotext", "qpdf", "pdfunite"],
        },
    ]
