"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Image Resizer",
            "category": "Advanced Imaging",
            "description": "Image Resizer. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_resizer",
            "cli_command": "image-resizer",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Cropper",
            "category": "Advanced Imaging",
            "description": "Image Cropper. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_cropper",
            "cli_command": "image-cropper",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Rotator",
            "category": "Advanced Imaging",
            "description": "Image Rotator. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_rotator",
            "cli_command": "image-rotator",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Flipper",
            "category": "Advanced Imaging",
            "description": "Image Flipper. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_flipper",
            "cli_command": "image-flipper",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Converter",
            "category": "Advanced Imaging",
            "description": "Image Converter. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_converter",
            "cli_command": "image-converter",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Optimizer",
            "category": "Advanced Imaging",
            "description": "Image Optimizer. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_optimizer",
            "cli_command": "image-optimizer",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Metadata Cleaner",
            "category": "Advanced Imaging",
            "description": "Image Metadata Cleaner. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_metadata_cleaner",
            "cli_command": "image-metadata-cleaner",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Contact Sheet",
            "category": "Advanced Imaging",
            "description": "Image Contact Sheet. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_contact_sheet",
            "cli_command": "image-contact-sheet",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Montage Builder",
            "category": "Advanced Imaging",
            "description": "Image Montage Builder. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_montage_builder",
            "cli_command": "image-montage-builder",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Border Adder",
            "category": "Advanced Imaging",
            "description": "Image Border Adder. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_border_adder",
            "cli_command": "image-border-adder",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Watermark Tool",
            "category": "Advanced Imaging",
            "description": "Image Watermark Tool. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_watermark_tool",
            "cli_command": "image-watermark-tool",
            "dependencies": ["Pillow"],
        },
        {
            "name": "Image Batch Renamer",
            "category": "Advanced Imaging",
            "description": "Image Batch Renamer. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.image_batch_renamer",
            "cli_command": "image-batch-renamer",
            "dependencies": ["Pillow"],
        },
    ]
