"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "System Summary",
            "category": "System Information",
            "description": "Summarize system summary at a glance.",
            "handler": "operations.system_summary",
            "cli_command": "system-summary",
            "dependencies": [],
        },
        {
            "name": "OS Version",
            "category": "System Information",
            "description": "OS Version: query and display os version details as structured JSON.",
            "handler": "operations.os_version",
            "cli_command": "os-version",
            "dependencies": [],
        },
        {
            "name": "Computer Name",
            "category": "System Information",
            "description": "Computer Name: query and display computer name details as structured JSON.",
            "handler": "operations.computer_name",
            "cli_command": "computer-name",
            "dependencies": [],
        },
        {
            "name": "CPU Information",
            "category": "System Information",
            "description": "CPU Information: query and display cpu information details as structured JSON.",
            "handler": "operations.cpu_information",
            "cli_command": "cpu-information",
            "dependencies": [],
        },
        {
            "name": "Memory Information",
            "category": "System Information",
            "description": "Memory Information: query and display memory information details as structured JSON.",
            "handler": "operations.memory_information",
            "cli_command": "memory-information",
            "dependencies": [],
        },
        {
            "name": "Boot Time",
            "category": "System Information",
            "description": "Boot Time: query and display boot time details as structured JSON.",
            "handler": "operations.boot_time",
            "cli_command": "boot-time",
            "dependencies": [],
        },
        {
            "name": "Current User",
            "category": "System Information",
            "description": "Current User: query and display current user details as structured JSON.",
            "handler": "operations.current_user",
            "cli_command": "current-user",
            "dependencies": [],
        },
        {
            "name": "Python Environment",
            "category": "System Information",
            "description": "Python Environment: query and display python environment details as structured JSON.",
            "handler": "operations.python_environment",
            "cli_command": "python-environment",
            "dependencies": [],
        },
        {
            "name": "Environment Report",
            "category": "System Information",
            "description": "Environment Report: query and display environment report details as structured JSON.",
            "handler": "operations.environment_report",
            "cli_command": "environment-report",
            "dependencies": [],
        },
        {
            "name": "Locale Information",
            "category": "System Information",
            "description": "Locale Information: query and display locale information details as structured JSON.",
            "handler": "operations.locale_information",
            "cli_command": "locale-information",
            "dependencies": [],
        },
        {
            "name": "Time Zone Information",
            "category": "System Information",
            "description": "Time Zone Information: query and display time zone information details as structured JSON.",
            "handler": "operations.time_zone_information",
            "cli_command": "time-zone-information",
            "dependencies": [],
        },
        {
            "name": "System Uptime",
            "category": "System Information",
            "description": "System Uptime: query and display system uptime details as structured JSON.",
            "handler": "operations.system_uptime",
            "cli_command": "system-uptime",
            "dependencies": [],
        },
        {
            "name": "Machine Architecture",
            "category": "System Information",
            "description": "Machine Architecture: query and display machine architecture details as structured JSON.",
            "handler": "operations.machine_architecture",
            "cli_command": "machine-architecture",
            "dependencies": [],
        },
        {
            "name": "System Directory Report",
            "category": "System Information",
            "description": "System Directory Report: query and display system directory report details as structured JSON.",
            "handler": "operations.system_directory_report",
            "cli_command": "system-directory-report",
            "dependencies": [],
        },
        {
            "name": "Temporary Directory Report",
            "category": "System Information",
            "description": "Temporary Directory Report: query and display temporary directory report details as structured JSON.",
            "handler": "operations.temporary_directory_report",
            "cli_command": "temporary-directory-report",
            "dependencies": [],
        },
        {
            "name": "User Profile Report",
            "category": "System Information",
            "description": "User Profile Report: query and display user profile report details as structured JSON.",
            "handler": "operations.user_profile_report",
            "cli_command": "user-profile-report",
            "dependencies": [],
        },
        {
            "name": "PowerShell Version",
            "category": "System Information",
            "description": "PowerShell Version: query and display powershell version details as structured JSON.",
            "handler": "operations.powershell_version",
            "cli_command": "powershell-version",
            "dependencies": ["powershell"],
        },
        {
            "name": "Windows Version Report",
            "category": "System Information",
            "description": "Windows Version Report: query and display windows version report details as structured JSON.",
            "handler": "operations.windows_version_report",
            "cli_command": "windows-version-report",
            "dependencies": [],
        },
        {
            "name": "Installed RAM Summary",
            "category": "System Information",
            "description": "Summarize installed ram summary at a glance.",
            "handler": "operations.installed_ram_summary",
            "cli_command": "installed-ram-summary",
            "dependencies": [],
        },
        {
            "name": "System Environment Export",
            "category": "System Information",
            "description": "System Environment Export: query and display system environment export details as structured JSON.",
            "handler": "operations.system_environment_export",
            "cli_command": "system-environment-export",
            "dependencies": [],
        },
    ]
