"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "System Summary",
            "category": "System Information",
            "description": "Summarize system summary at a glance.",
            "handler": "operations.system_summary",
            "cli_command": "system-summary",
            "dependencies": [],
        },
        {
            "name": "OS Version",
            "category": "System Information",
            "description": "Summarize system summary at a glance.",
            "handler": "operations.os_version",
            "cli_command": "os-version",
            "dependencies": [],
        },
        {
            "name": "Computer Name",
            "category": "System Information",
            "description": "OS Version: run the 'os version' operation and print structured JSON results.",
            "handler": "operations.computer_name",
            "cli_command": "computer-name",
            "dependencies": [],
        },
        {
            "name": "CPU Information",
            "category": "System Information",
            "description": "Computer Name: run the 'computer name' operation and print structured JSON results.",
            "handler": "operations.cpu_information",
            "cli_command": "cpu-information",
            "dependencies": [],
        },
        {
            "name": "Memory Information",
            "category": "System Information",
            "description": "CPU Information: run the 'cpu information' operation and print structured JSON results.",
            "handler": "operations.memory_information",
            "cli_command": "memory-information",
            "dependencies": [],
        },
        {
            "name": "Boot Time",
            "category": "System Information",
            "description": "Memory Information: run the 'memory information' operation and print structured JSON results.",
            "handler": "operations.boot_time",
            "cli_command": "boot-time",
            "dependencies": [],
        },
        {
            "name": "Current User",
            "category": "System Information",
            "description": "Compute boot time values.",
            "handler": "operations.current_user",
            "cli_command": "current-user",
            "dependencies": [],
        },
        {
            "name": "Python Environment",
            "category": "System Information",
            "description": "Current User: run the 'current user' operation and print structured JSON results.",
            "handler": "operations.python_environment",
            "cli_command": "python-environment",
            "dependencies": [],
        },
        {
            "name": "Environment Report",
            "category": "System Information",
            "description": "Python Environment: run the 'python environment' operation and print structured JSON results.",
            "handler": "operations.environment_report",
            "cli_command": "environment-report",
            "dependencies": [],
        },
        {
            "name": "Locale Information",
            "category": "System Information",
            "description": "Compile a readable environment report report.",
            "handler": "operations.locale_information",
            "cli_command": "locale-information",
            "dependencies": [],
        },
        {
            "name": "Time Zone Information",
            "category": "System Information",
            "description": "Locale Information: run the 'locale information' operation and print structured JSON results.",
            "handler": "operations.time_zone_information",
            "cli_command": "time-zone-information",
            "dependencies": [],
        },
        {
            "name": "System Uptime",
            "category": "System Information",
            "description": "Time Zone Information: run the 'time zone information' operation and print structured JSON results.",
            "handler": "operations.system_uptime",
            "cli_command": "system-uptime",
            "dependencies": [],
        },
        {
            "name": "Machine Architecture",
            "category": "System Information",
            "description": "System Uptime: run the 'system uptime' operation and print structured JSON results.",
            "handler": "operations.machine_architecture",
            "cli_command": "machine-architecture",
            "dependencies": [],
        },
        {
            "name": "System Directory Report",
            "category": "System Information",
            "description": "Machine Architecture: run the 'machine architecture' operation and print structured JSON results.",
            "handler": "operations.system_directory_report",
            "cli_command": "system-directory-report",
            "dependencies": [],
        },
        {
            "name": "Temporary Directory Report",
            "category": "System Information",
            "description": "Compile a readable system directory report report.",
            "handler": "operations.temporary_directory_report",
            "cli_command": "temporary-directory-report",
            "dependencies": [],
        },
        {
            "name": "User Profile Report",
            "category": "System Information",
            "description": "Compile a readable temporary directory report report.",
            "handler": "operations.user_profile_report",
            "cli_command": "user-profile-report",
            "dependencies": [],
        },
        {
            "name": "PowerShell Version",
            "category": "System Information",
            "description": "Compile a readable user profile report report.",
            "handler": "operations.powershell_version",
            "cli_command": "powershell-version",
            "dependencies": ["powershell"],
        },
        {
            "name": "Windows Version Report",
            "category": "System Information",
            "description": "PowerShell Version: run the 'powershell version' operation and print structured JSON results.",
            "handler": "operations.windows_version_report",
            "cli_command": "windows-version-report",
            "dependencies": [],
        },
        {
            "name": "Installed RAM Summary",
            "category": "System Information",
            "description": "Summarize installed ram summary at a glance.",
            "handler": "operations.installed_ram_summary",
            "cli_command": "installed-ram-summary",
            "dependencies": [],
        },
        {
            "name": "System Environment Export",
            "category": "System Information",
            "description": "Summarize installed ram summary at a glance.",
            "handler": "operations.system_environment_export",
            "cli_command": "system-environment-export",
            "dependencies": [],
        },
    ]
