"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "System Summary",
            "category": "System Information",
            "description": "System Summary: system-summary operation.",
            "handler": "operations.system_summary",
            "cli_command": "system-summary",
            "dependencies": [],
        },
        {
            "name": "OS Version",
            "category": "System Information",
            "description": "OS Version: os-version operation.",
            "handler": "operations.os_version",
            "cli_command": "os-version",
            "dependencies": [],
        },
        {
            "name": "Computer Name",
            "category": "System Information",
            "description": "Computer Name: computer-name operation.",
            "handler": "operations.computer_name",
            "cli_command": "computer-name",
            "dependencies": [],
        },
        {
            "name": "CPU Information",
            "category": "System Information",
            "description": "CPU Information: cpu-information operation.",
            "handler": "operations.cpu_information",
            "cli_command": "cpu-information",
            "dependencies": [],
        },
        {
            "name": "Memory Information",
            "category": "System Information",
            "description": "Memory Information: memory-information operation.",
            "handler": "operations.memory_information",
            "cli_command": "memory-information",
            "dependencies": [],
        },
        {
            "name": "Boot Time",
            "category": "System Information",
            "description": "Boot Time: boot-time operation.",
            "handler": "operations.boot_time",
            "cli_command": "boot-time",
            "dependencies": [],
        },
        {
            "name": "Current User",
            "category": "System Information",
            "description": "Current User: current-user operation.",
            "handler": "operations.current_user",
            "cli_command": "current-user",
            "dependencies": [],
        },
        {
            "name": "Python Environment",
            "category": "System Information",
            "description": "Python Environment: python-environment operation.",
            "handler": "operations.python_environment",
            "cli_command": "python-environment",
            "dependencies": [],
        },
        {
            "name": "Environment Report",
            "category": "System Information",
            "description": "Environment Report: environment-report operation.",
            "handler": "operations.environment_report",
            "cli_command": "environment-report",
            "dependencies": [],
        },
        {
            "name": "Locale Information",
            "category": "System Information",
            "description": "Locale Information: locale-information operation.",
            "handler": "operations.locale_information",
            "cli_command": "locale-information",
            "dependencies": [],
        },
        {
            "name": "Time Zone Information",
            "category": "System Information",
            "description": "Time Zone Information: time-zone-information operation.",
            "handler": "operations.time_zone_information",
            "cli_command": "time-zone-information",
            "dependencies": [],
        },
        {
            "name": "System Uptime",
            "category": "System Information",
            "description": "System Uptime: system-uptime operation.",
            "handler": "operations.system_uptime",
            "cli_command": "system-uptime",
            "dependencies": [],
        },
        {
            "name": "Machine Architecture",
            "category": "System Information",
            "description": "Machine Architecture: machine-architecture operation.",
            "handler": "operations.machine_architecture",
            "cli_command": "machine-architecture",
            "dependencies": [],
        },
        {
            "name": "System Directory Report",
            "category": "System Information",
            "description": "System Directory Report: system-directory-report operation.",
            "handler": "operations.system_directory_report",
            "cli_command": "system-directory-report",
            "dependencies": [],
        },
        {
            "name": "Temporary Directory Report",
            "category": "System Information",
            "description": "Temporary Directory Report: temporary-directory-report operation.",
            "handler": "operations.temporary_directory_report",
            "cli_command": "temporary-directory-report",
            "dependencies": [],
        },
        {
            "name": "User Profile Report",
            "category": "System Information",
            "description": "User Profile Report: user-profile-report operation.",
            "handler": "operations.user_profile_report",
            "cli_command": "user-profile-report",
            "dependencies": [],
        },
        {
            "name": "PowerShell Version",
            "category": "System Information",
            "description": "PowerShell Version: powershell-version operation.",
            "handler": "operations.powershell_version",
            "cli_command": "powershell-version",
            "dependencies": ["powershell"],
        },
        {
            "name": "Windows Version Report",
            "category": "System Information",
            "description": "Windows Version Report: windows-version-report operation.",
            "handler": "operations.windows_version_report",
            "cli_command": "windows-version-report",
            "dependencies": [],
        },
        {
            "name": "Installed RAM Summary",
            "category": "System Information",
            "description": "Installed RAM Summary: installed-ram-summary operation.",
            "handler": "operations.installed_ram_summary",
            "cli_command": "installed-ram-summary",
            "dependencies": [],
        },
        {
            "name": "System Environment Export",
            "category": "System Information",
            "description": "System Environment Export: system-environment-export operation.",
            "handler": "operations.system_environment_export",
            "cli_command": "system-environment-export",
            "dependencies": [],
        },
    ]
