"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Bytes Converter",
            "category": "Unit Conversion",
            "description": "Bytes Converter: bytes-converter operation.",
            "handler": "operations.bytes_converter",
            "cli_command": "bytes-converter",
            "dependencies": [],
        },
        {
            "name": "Size Formatter",
            "category": "Unit Conversion",
            "description": "Size Formatter: size-formatter operation.",
            "handler": "operations.size_formatter",
            "cli_command": "size-formatter",
            "dependencies": [],
        },
        {
            "name": "Seconds Converter",
            "category": "Unit Conversion",
            "description": "Seconds Converter: seconds-converter operation.",
            "handler": "operations.seconds_converter",
            "cli_command": "seconds-converter",
            "dependencies": [],
        },
        {
            "name": "Temperature Converter",
            "category": "Unit Conversion",
            "description": "Temperature Converter: temperature-converter operation.",
            "handler": "operations.temperature_converter",
            "cli_command": "temperature-converter",
            "dependencies": [],
        },
        {
            "name": "Length Converter",
            "category": "Unit Conversion",
            "description": "Length Converter: length-converter operation.",
            "handler": "operations.length_converter",
            "cli_command": "length-converter",
            "dependencies": [],
        },
        {
            "name": "Mass Converter",
            "category": "Unit Conversion",
            "description": "Mass Converter: mass-converter operation.",
            "handler": "operations.mass_converter",
            "cli_command": "mass-converter",
            "dependencies": [],
        },
        {
            "name": "Area Converter",
            "category": "Unit Conversion",
            "description": "Area Converter: area-converter operation.",
            "handler": "operations.area_converter",
            "cli_command": "area-converter",
            "dependencies": [],
        },
        {
            "name": "Volume Converter",
            "category": "Unit Conversion",
            "description": "Volume Converter: volume-converter operation.",
            "handler": "operations.volume_converter",
            "cli_command": "volume-converter",
            "dependencies": [],
        },
        {
            "name": "Speed Converter",
            "category": "Unit Conversion",
            "description": "Speed Converter: speed-converter operation.",
            "handler": "operations.speed_converter",
            "cli_command": "speed-converter",
            "dependencies": [],
        },
        {
            "name": "Pressure Converter",
            "category": "Unit Conversion",
            "description": "Pressure Converter: pressure-converter operation.",
            "handler": "operations.pressure_converter",
            "cli_command": "pressure-converter",
            "dependencies": [],
        },
        {
            "name": "Energy Converter",
            "category": "Unit Conversion",
            "description": "Energy Converter: energy-converter operation.",
            "handler": "operations.energy_converter",
            "cli_command": "energy-converter",
            "dependencies": [],
        },
        {
            "name": "Power Converter",
            "category": "Unit Conversion",
            "description": "Power Converter: power-converter operation.",
            "handler": "operations.power_converter",
            "cli_command": "power-converter",
            "dependencies": [],
        },
        {
            "name": "Angle Converter",
            "category": "Unit Conversion",
            "description": "Angle Converter: angle-converter operation.",
            "handler": "operations.angle_converter",
            "cli_command": "angle-converter",
            "dependencies": [],
        },
        {
            "name": "Frequency Converter",
            "category": "Unit Conversion",
            "description": "Frequency Converter: frequency-converter operation.",
            "handler": "operations.frequency_converter",
            "cli_command": "frequency-converter",
            "dependencies": [],
        },
        {
            "name": "Data Rate Converter",
            "category": "Unit Conversion",
            "description": "Data Rate Converter: data-rate-converter operation.",
            "handler": "operations.data_rate_converter",
            "cli_command": "data-rate-converter",
            "dependencies": [],
        },
    ]
