"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Bytes Converter",
            "category": "Unit Conversion",
            "description": "Bytes Converter: performs the bytes converter action with structured, human-readable output.",
            "handler": "operations.bytes_converter",
            "cli_command": "bytes-converter",
            "dependencies": [],
        },
        {
            "name": "Size Formatter",
            "category": "Unit Conversion",
            "description": "Size Formatter: performs the size formatter action with structured, human-readable output.",
            "handler": "operations.size_formatter",
            "cli_command": "size-formatter",
            "dependencies": [],
        },
        {
            "name": "Seconds Converter",
            "category": "Unit Conversion",
            "description": "Seconds Converter: performs the seconds converter action with structured, human-readable output.",
            "handler": "operations.seconds_converter",
            "cli_command": "seconds-converter",
            "dependencies": [],
        },
        {
            "name": "Temperature Converter",
            "category": "Unit Conversion",
            "description": "Temperature Converter: performs the temperature converter action with structured, human-readable output.",
            "handler": "operations.temperature_converter",
            "cli_command": "temperature-converter",
            "dependencies": [],
        },
        {
            "name": "Length Converter",
            "category": "Unit Conversion",
            "description": "Length Converter: performs the length converter action with structured, human-readable output.",
            "handler": "operations.length_converter",
            "cli_command": "length-converter",
            "dependencies": [],
        },
        {
            "name": "Mass Converter",
            "category": "Unit Conversion",
            "description": "Mass Converter: performs the mass converter action with structured, human-readable output.",
            "handler": "operations.mass_converter",
            "cli_command": "mass-converter",
            "dependencies": [],
        },
        {
            "name": "Area Converter",
            "category": "Unit Conversion",
            "description": "Area Converter: performs the area converter action with structured, human-readable output.",
            "handler": "operations.area_converter",
            "cli_command": "area-converter",
            "dependencies": [],
        },
        {
            "name": "Volume Converter",
            "category": "Unit Conversion",
            "description": "Volume Converter: performs the volume converter action with structured, human-readable output.",
            "handler": "operations.volume_converter",
            "cli_command": "volume-converter",
            "dependencies": [],
        },
        {
            "name": "Speed Converter",
            "category": "Unit Conversion",
            "description": "Speed Converter: performs the speed converter action with structured, human-readable output.",
            "handler": "operations.speed_converter",
            "cli_command": "speed-converter",
            "dependencies": [],
        },
        {
            "name": "Pressure Converter",
            "category": "Unit Conversion",
            "description": "Pressure Converter: performs the pressure converter action with structured, human-readable output.",
            "handler": "operations.pressure_converter",
            "cli_command": "pressure-converter",
            "dependencies": [],
        },
        {
            "name": "Energy Converter",
            "category": "Unit Conversion",
            "description": "Energy Converter: performs the energy converter action with structured, human-readable output.",
            "handler": "operations.energy_converter",
            "cli_command": "energy-converter",
            "dependencies": [],
        },
        {
            "name": "Power Converter",
            "category": "Unit Conversion",
            "description": "Power Converter: performs the power converter action with structured, human-readable output.",
            "handler": "operations.power_converter",
            "cli_command": "power-converter",
            "dependencies": [],
        },
        {
            "name": "Angle Converter",
            "category": "Unit Conversion",
            "description": "Angle Converter: performs the angle converter action with structured, human-readable output.",
            "handler": "operations.angle_converter",
            "cli_command": "angle-converter",
            "dependencies": [],
        },
        {
            "name": "Frequency Converter",
            "category": "Unit Conversion",
            "description": "Frequency Converter: performs the frequency converter action with structured, human-readable output.",
            "handler": "operations.frequency_converter",
            "cli_command": "frequency-converter",
            "dependencies": [],
        },
        {
            "name": "Data Rate Converter",
            "category": "Unit Conversion",
            "description": "Data Rate Converter: performs the data rate converter action with structured, human-readable output.",
            "handler": "operations.data_rate_converter",
            "cli_command": "data-rate-converter",
            "dependencies": [],
        },
    ]
