"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Registry Query",
            "category": "Registry Tools",
            "description": "Registry Query: query and display registry query details as structured JSON.",
            "handler": "operations.registry_query",
            "cli_command": "registry-query",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Export",
            "category": "Registry Tools",
            "description": "Registry Export: query and display registry export details as structured JSON.",
            "handler": "operations.registry_export",
            "cli_command": "registry-export",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Import",
            "category": "Registry Tools",
            "description": "Registry Import: query and display registry import details as structured JSON.",
            "handler": "operations.registry_import",
            "cli_command": "registry-import",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Key Creator",
            "category": "Registry Tools",
            "description": "Registry Key Creator: query and display registry key creator details as structured JSON.",
            "handler": "operations.registry_key_creator",
            "cli_command": "registry-key-creator",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Key Deleter",
            "category": "Registry Tools",
            "description": "Registry Key Deleter: query and display registry key deleter details as structured JSON.",
            "handler": "operations.registry_key_deleter",
            "cli_command": "registry-key-deleter",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Value Setter",
            "category": "Registry Tools",
            "description": "Registry Value Setter: query and display registry value setter details as structured JSON.",
            "handler": "operations.registry_value_setter",
            "cli_command": "registry-value-setter",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Value Deleter",
            "category": "Registry Tools",
            "description": "Registry Value Deleter: query and display registry value deleter details as structured JSON.",
            "handler": "operations.registry_value_deleter",
            "cli_command": "registry-value-deleter",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Value Enumerator",
            "category": "Registry Tools",
            "description": "Registry Value Enumerator: query and display registry value enumerator details as structured JSON.",
            "handler": "operations.registry_value_enumerator",
            "cli_command": "registry-value-enumerator",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Backup",
            "category": "Registry Tools",
            "description": "Registry Backup: query and display registry backup details as structured JSON.",
            "handler": "operations.registry_backup",
            "cli_command": "registry-backup",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Path Validator",
            "category": "Registry Tools",
            "description": "Validate registry path structure or content.",
            "handler": "operations.registry_path_validator",
            "cli_command": "registry-path-validator",
            "dependencies": ["reg"],
        },
    ]
