"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Registry Query",
            "category": "Registry Tools",
            "description": "Registry Query: performs the registry query action with structured, human-readable output.",
            "handler": "operations.registry_query",
            "cli_command": "registry-query",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Export",
            "category": "Registry Tools",
            "description": "Registry Export: performs the registry export action with structured, human-readable output.",
            "handler": "operations.registry_export",
            "cli_command": "registry-export",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Import",
            "category": "Registry Tools",
            "description": "Registry Import: performs the registry import action with structured, human-readable output.",
            "handler": "operations.registry_import",
            "cli_command": "registry-import",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Key Creator",
            "category": "Registry Tools",
            "description": "Registry Key Creator: performs the registry key creator action with structured, human-readable output.",
            "handler": "operations.registry_key_creator",
            "cli_command": "registry-key-creator",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Key Deleter",
            "category": "Registry Tools",
            "description": "Registry Key Deleter: performs the registry key deleter action with structured, human-readable output.",
            "handler": "operations.registry_key_deleter",
            "cli_command": "registry-key-deleter",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Value Setter",
            "category": "Registry Tools",
            "description": "Registry Value Setter: performs the registry value setter action with structured, human-readable output.",
            "handler": "operations.registry_value_setter",
            "cli_command": "registry-value-setter",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Value Deleter",
            "category": "Registry Tools",
            "description": "Registry Value Deleter: performs the registry value deleter action with structured, human-readable output.",
            "handler": "operations.registry_value_deleter",
            "cli_command": "registry-value-deleter",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Value Enumerator",
            "category": "Registry Tools",
            "description": "Registry Value Enumerator: performs the registry value enumerator action with structured, human-readable output.",
            "handler": "operations.registry_value_enumerator",
            "cli_command": "registry-value-enumerator",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Backup",
            "category": "Registry Tools",
            "description": "Registry Backup: performs the registry backup action with structured, human-readable output.",
            "handler": "operations.registry_backup",
            "cli_command": "registry-backup",
            "dependencies": ["reg"],
        },
        {
            "name": "Registry Path Validator",
            "category": "Registry Tools",
            "description": "Registry Path Validator: performs the registry path validator action with structured, human-readable output.",
            "handler": "operations.registry_path_validator",
            "cli_command": "registry-path-validator",
            "dependencies": ["reg"],
        },
    ]
