"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Event Log List",
            "category": "Event Tools",
            "description": "List event log entries.",
            "handler": "operations.event_log_list",
            "cli_command": "event-log-list",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Query",
            "category": "Event Tools",
            "description": "Event Log Query: query and display event log query details as structured JSON.",
            "handler": "operations.event_log_query",
            "cli_command": "event-log-query",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Export",
            "category": "Event Tools",
            "description": "Event Log Export: query and display event log export details as structured JSON.",
            "handler": "operations.event_log_export",
            "cli_command": "event-log-export",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Source Search",
            "category": "Event Tools",
            "description": "Event Log Source Search: query and display event log source search details as structured JSON.",
            "handler": "operations.event_log_source_search",
            "cli_command": "event-log-source-search",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Level Summary",
            "category": "Event Tools",
            "description": "Summarize event log level summary at a glance.",
            "handler": "operations.event_log_level_summary",
            "cli_command": "event-log-level-summary",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Time Filter",
            "category": "Event Tools",
            "description": "Filter event log time by criteria.",
            "handler": "operations.event_log_time_filter",
            "cli_command": "event-log-time-filter",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Keyword Filter",
            "category": "Event Tools",
            "description": "Filter event log keyword by criteria.",
            "handler": "operations.event_log_keyword_filter",
            "cli_command": "event-log-keyword-filter",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Statistics",
            "category": "Event Tools",
            "description": "Event Log Statistics: query and display event log statistics details as structured JSON.",
            "handler": "operations.event_log_statistics",
            "cli_command": "event-log-statistics",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Recent Errors",
            "category": "Event Tools",
            "description": "Event Log Recent Errors: query and display event log recent errors details as structured JSON.",
            "handler": "operations.event_log_recent_errors",
            "cli_command": "event-log-recent-errors",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Recent Warnings",
            "category": "Event Tools",
            "description": "Event Log Recent Warnings: query and display event log recent warnings details as structured JSON.",
            "handler": "operations.event_log_recent_warnings",
            "cli_command": "event-log-recent-warnings",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Channel Inventory",
            "category": "Event Tools",
            "description": "Enumerate an inventory of event log channel inventory.",
            "handler": "operations.event_log_channel_inventory",
            "cli_command": "event-log-channel-inventory",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Guide",
            "category": "Event Tools",
            "description": "Show guidance for event log.",
            "handler": "operations.event_log_guide",
            "cli_command": "event-log-guide",
            "dependencies": ["wevtutil"],
        },
    ]
