"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Event Log List",
            "category": "Event Tools",
            "description": "Event Log List: event-log-list operation.",
            "handler": "operations.event_log_list",
            "cli_command": "event-log-list",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Query",
            "category": "Event Tools",
            "description": "Event Log Query: event-log-query operation.",
            "handler": "operations.event_log_query",
            "cli_command": "event-log-query",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Export",
            "category": "Event Tools",
            "description": "Event Log Export: event-log-export operation.",
            "handler": "operations.event_log_export",
            "cli_command": "event-log-export",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Source Search",
            "category": "Event Tools",
            "description": "Event Log Source Search: event-log-source-search operation.",
            "handler": "operations.event_log_source_search",
            "cli_command": "event-log-source-search",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Level Summary",
            "category": "Event Tools",
            "description": "Event Log Level Summary: event-log-level-summary operation.",
            "handler": "operations.event_log_level_summary",
            "cli_command": "event-log-level-summary",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Time Filter",
            "category": "Event Tools",
            "description": "Event Log Time Filter: event-log-time-filter operation.",
            "handler": "operations.event_log_time_filter",
            "cli_command": "event-log-time-filter",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Keyword Filter",
            "category": "Event Tools",
            "description": "Event Log Keyword Filter: event-log-keyword-filter operation.",
            "handler": "operations.event_log_keyword_filter",
            "cli_command": "event-log-keyword-filter",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Statistics",
            "category": "Event Tools",
            "description": "Event Log Statistics: event-log-statistics operation.",
            "handler": "operations.event_log_statistics",
            "cli_command": "event-log-statistics",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Recent Errors",
            "category": "Event Tools",
            "description": "Event Log Recent Errors: event-log-recent-errors operation.",
            "handler": "operations.event_log_recent_errors",
            "cli_command": "event-log-recent-errors",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Recent Warnings",
            "category": "Event Tools",
            "description": "Event Log Recent Warnings: event-log-recent-warnings operation.",
            "handler": "operations.event_log_recent_warnings",
            "cli_command": "event-log-recent-warnings",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Channel Inventory",
            "category": "Event Tools",
            "description": "Event Log Channel Inventory: event-log-channel-inventory operation.",
            "handler": "operations.event_log_channel_inventory",
            "cli_command": "event-log-channel-inventory",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Guide",
            "category": "Event Tools",
            "description": "Event Log Guide: event-log-guide operation.",
            "handler": "operations.event_log_guide",
            "cli_command": "event-log-guide",
            "dependencies": ["wevtutil"],
        },
    ]
