"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Event Log List",
            "category": "Event Tools",
            "description": "Event Log List: performs the event log list action with structured, human-readable output.",
            "handler": "operations.event_log_list",
            "cli_command": "event-log-list",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Query",
            "category": "Event Tools",
            "description": "Event Log Query: performs the event log query action with structured, human-readable output.",
            "handler": "operations.event_log_query",
            "cli_command": "event-log-query",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Export",
            "category": "Event Tools",
            "description": "Event Log Export: performs the event log export action with structured, human-readable output.",
            "handler": "operations.event_log_export",
            "cli_command": "event-log-export",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Source Search",
            "category": "Event Tools",
            "description": "Event Log Source Search: performs the event log source search action with structured, human-readable output.",
            "handler": "operations.event_log_source_search",
            "cli_command": "event-log-source-search",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Level Summary",
            "category": "Event Tools",
            "description": "Event Log Level Summary: performs the event log level summary action with structured, human-readable output.",
            "handler": "operations.event_log_level_summary",
            "cli_command": "event-log-level-summary",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Time Filter",
            "category": "Event Tools",
            "description": "Event Log Time Filter: performs the event log time filter action with structured, human-readable output.",
            "handler": "operations.event_log_time_filter",
            "cli_command": "event-log-time-filter",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Keyword Filter",
            "category": "Event Tools",
            "description": "Event Log Keyword Filter: performs the event log keyword filter action with structured, human-readable output.",
            "handler": "operations.event_log_keyword_filter",
            "cli_command": "event-log-keyword-filter",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Statistics",
            "category": "Event Tools",
            "description": "Event Log Statistics: performs the event log statistics action with structured, human-readable output.",
            "handler": "operations.event_log_statistics",
            "cli_command": "event-log-statistics",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Recent Errors",
            "category": "Event Tools",
            "description": "Event Log Recent Errors: performs the event log recent errors action with structured, human-readable output.",
            "handler": "operations.event_log_recent_errors",
            "cli_command": "event-log-recent-errors",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Recent Warnings",
            "category": "Event Tools",
            "description": "Event Log Recent Warnings: performs the event log recent warnings action with structured, human-readable output.",
            "handler": "operations.event_log_recent_warnings",
            "cli_command": "event-log-recent-warnings",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Channel Inventory",
            "category": "Event Tools",
            "description": "Event Log Channel Inventory: performs the event log channel inventory action with structured, human-readable output.",
            "handler": "operations.event_log_channel_inventory",
            "cli_command": "event-log-channel-inventory",
            "dependencies": ["wevtutil"],
        },
        {
            "name": "Event Log Guide",
            "category": "Event Tools",
            "description": "Event Log Guide: performs the event log guide action with structured, human-readable output.",
            "handler": "operations.event_log_guide",
            "cli_command": "event-log-guide",
            "dependencies": ["wevtutil"],
        },
    ]
