"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Driver List",
            "category": "Driver Tools",
            "description": "Driver List: driver-list operation.",
            "handler": "operations.driver_list",
            "cli_command": "driver-list",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Details",
            "category": "Driver Tools",
            "description": "Driver Details: driver-details operation.",
            "handler": "operations.driver_details",
            "cli_command": "driver-details",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Package Inventory",
            "category": "Driver Tools",
            "description": "Inventory installed driver packages and published driver metadata.",
            "handler": "operations.driver_backup",
            "cli_command": "driver-package-inventory",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Store Inventory",
            "category": "Driver Tools",
            "description": "Driver Store Inventory: driver-store-inventory operation.",
            "handler": "operations.driver_store_inventory",
            "cli_command": "driver-store-inventory",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Signature Check",
            "category": "Driver Tools",
            "description": "Driver Signature Check: driver-signature-check operation.",
            "handler": "operations.driver_signature_check",
            "cli_command": "driver-signature-check",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Version Report",
            "category": "Driver Tools",
            "description": "Driver Version Report: driver-version-report operation.",
            "handler": "operations.driver_version_report",
            "cli_command": "driver-version-report",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Provider Report",
            "category": "Driver Tools",
            "description": "Driver Provider Report: driver-provider-report operation.",
            "handler": "operations.driver_provider_report",
            "cli_command": "driver-provider-report",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Class Report",
            "category": "Driver Tools",
            "description": "Driver Class Report: driver-class-report operation.",
            "handler": "operations.driver_class_report",
            "cli_command": "driver-class-report",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Device Status",
            "category": "Driver Tools",
            "description": "Driver Device Status: driver-device-status operation.",
            "handler": "operations.driver_device_status",
            "cli_command": "driver-device-status",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Update Reminder",
            "category": "Driver Tools",
            "description": "Driver Update Reminder: driver-update-reminder operation.",
            "handler": "operations.driver_update_reminder",
            "cli_command": "driver-update-reminder",
            "dependencies": ["pnputil"],
        },
    ]
