"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Driver List",
            "category": "Driver Tools",
            "description": "Driver List. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_list",
            "cli_command": "driver-list",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Details",
            "category": "Driver Tools",
            "description": "Driver Details. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_details",
            "cli_command": "driver-details",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Package Inventory",
            "category": "Driver Tools",
            "description": "Inventory installed driver packages and published driver metadata.",
            "handler": "operations.driver_backup",
            "cli_command": "driver-package-inventory",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Store Inventory",
            "category": "Driver Tools",
            "description": "Driver Store Inventory. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_store_inventory",
            "cli_command": "driver-store-inventory",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Signature Check",
            "category": "Driver Tools",
            "description": "Driver Signature Check. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_signature_check",
            "cli_command": "driver-signature-check",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Version Report",
            "category": "Driver Tools",
            "description": "Driver Version Report. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_version_report",
            "cli_command": "driver-version-report",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Provider Report",
            "category": "Driver Tools",
            "description": "Driver Provider Report. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_provider_report",
            "cli_command": "driver-provider-report",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Class Report",
            "category": "Driver Tools",
            "description": "Driver Class Report. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_class_report",
            "cli_command": "driver-class-report",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Device Status",
            "category": "Driver Tools",
            "description": "Driver Device Status. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_device_status",
            "cli_command": "driver-device-status",
            "dependencies": ["pnputil"],
        },
        {
            "name": "Driver Update Reminder",
            "category": "Driver Tools",
            "description": "Driver Update Reminder. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.driver_update_reminder",
            "cli_command": "driver-update-reminder",
            "dependencies": ["pnputil"],
        },
    ]
