"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Shell Command Runner",
            "category": "Shell & Command Tools",
            "description": "Run shell command commands and capture output.",
            "handler": "operations.shell_command_runner",
            "cli_command": "shell-command-runner",
            "dependencies": [],
        },
        {
            "name": "PowerShell Command Runner",
            "category": "Shell & Command Tools",
            "description": "Run powershell command commands and capture output.",
            "handler": "operations.powershell_command_runner",
            "cli_command": "powershell-command-runner",
            "dependencies": ["powershell"],
        },
        {
            "name": "Command Resolver",
            "category": "Shell & Command Tools",
            "description": "Resolve command names to concrete targets.",
            "handler": "operations.command_resolver",
            "cli_command": "command-resolver",
            "dependencies": [],
        },
        {
            "name": "PATH Inspector",
            "category": "Shell & Command Tools",
            "description": "Inspect path and report internals.",
            "handler": "operations.path_inspector",
            "cli_command": "path-inspector",
            "dependencies": [],
        },
        {
            "name": "Executable Locator",
            "category": "Shell & Command Tools",
            "description": "Locate executable paths on disk.",
            "handler": "operations.executable_locator",
            "cli_command": "executable-locator",
            "dependencies": [],
        },
        {
            "name": "Command History Guide",
            "category": "Shell & Command Tools",
            "description": "Show guidance for command history.",
            "handler": "operations.command_history_guide",
            "cli_command": "command-history-guide",
            "dependencies": [],
        },
        {
            "name": "Shell Environment Dump",
            "category": "Shell & Command Tools",
            "description": "Dump shell environment contents in a readable format.",
            "handler": "operations.shell_environment_dump",
            "cli_command": "shell-environment-dump",
            "dependencies": [],
        },
        {
            "name": "Working Directory Reporter",
            "category": "Shell & Command Tools",
            "description": "Produce a detailed report of working directory.",
            "handler": "operations.working_directory_reporter",
            "cli_command": "working-directory-reporter",
            "dependencies": [],
        },
        {
            "name": "Command Timeout Runner",
            "category": "Shell & Command Tools",
            "description": "Run command timeout commands and capture output.",
            "handler": "operations.command_timeout_runner",
            "cli_command": "command-timeout-runner",
            "dependencies": [],
        },
        {
            "name": "Batch File Generator",
            "category": "Shell & Command Tools",
            "description": "Generate batch file output.",
            "handler": "operations.batch_file_generator",
            "cli_command": "batch-file-generator",
            "dependencies": [],
        },
        {
            "name": "PowerShell Script Generator",
            "category": "Shell & Command Tools",
            "description": "Generate powershell script output.",
            "handler": "operations.powershell_script_generator",
            "cli_command": "powershell-script-generator",
            "dependencies": [],
        },
        {
            "name": "Shell Quoting Helper",
            "category": "Shell & Command Tools",
            "description": "Assist with shell quoting tasks.",
            "handler": "operations.shell_quoting_helper",
            "cli_command": "shell-quoting-helper",
            "dependencies": [],
        },
        {
            "name": "Argument Escaper",
            "category": "Shell & Command Tools",
            "description": "Escape argument strings for safe shell use.",
            "handler": "operations.argument_escaper",
            "cli_command": "argument-escaper",
            "dependencies": [],
        },
        {
            "name": "Exit Code Decoder",
            "category": "Shell & Command Tools",
            "description": "Decode exit code.",
            "handler": "operations.exit_code_decoder",
            "cli_command": "exit-code-decoder",
            "dependencies": [],
        },
        {
            "name": "STDOUT Capture",
            "category": "Shell & Command Tools",
            "description": "Capture stdout streams from child processes.",
            "handler": "operations.stdout_capture",
            "cli_command": "stdout-capture",
            "dependencies": [],
        },
        {
            "name": "STDERR Capture",
            "category": "Shell & Command Tools",
            "description": "Capture stderr streams from child processes.",
            "handler": "operations.stderr_capture",
            "cli_command": "stderr-capture",
            "dependencies": [],
        },
        {
            "name": "Process Pipe Helper",
            "category": "Shell & Command Tools",
            "description": "Assist with process pipe tasks.",
            "handler": "operations.process_pipe_helper",
            "cli_command": "process-pipe-helper",
            "dependencies": [],
        },
        {
            "name": "Command Availability Scan",
            "category": "Shell & Command Tools",
            "description": "Command Availability Scan: command availability scan as structured JSON output.",
            "handler": "operations.command_availability_scan",
            "cli_command": "command-availability-scan",
            "dependencies": [],
        },
    ]
