"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Shell Command Runner",
            "category": "Shell & Command Tools",
            "description": "Shell Command Runner: shell-command-runner operation.",
            "handler": "operations.shell_command_runner",
            "cli_command": "shell-command-runner",
            "dependencies": [],
        },
        {
            "name": "PowerShell Command Runner",
            "category": "Shell & Command Tools",
            "description": "PowerShell Command Runner: powershell-command-runner operation.",
            "handler": "operations.powershell_command_runner",
            "cli_command": "powershell-command-runner",
            "dependencies": ["powershell"],
        },
        {
            "name": "Command Resolver",
            "category": "Shell & Command Tools",
            "description": "Command Resolver: command-resolver operation.",
            "handler": "operations.command_resolver",
            "cli_command": "command-resolver",
            "dependencies": [],
        },
        {
            "name": "PATH Inspector",
            "category": "Shell & Command Tools",
            "description": "PATH Inspector: path-inspector operation.",
            "handler": "operations.path_inspector",
            "cli_command": "path-inspector",
            "dependencies": [],
        },
        {
            "name": "Executable Locator",
            "category": "Shell & Command Tools",
            "description": "Executable Locator: executable-locator operation.",
            "handler": "operations.executable_locator",
            "cli_command": "executable-locator",
            "dependencies": [],
        },
        {
            "name": "Command History Guide",
            "category": "Shell & Command Tools",
            "description": "Command History Guide: command-history-guide operation.",
            "handler": "operations.command_history_guide",
            "cli_command": "command-history-guide",
            "dependencies": [],
        },
        {
            "name": "Shell Environment Dump",
            "category": "Shell & Command Tools",
            "description": "Shell Environment Dump: shell-environment-dump operation.",
            "handler": "operations.shell_environment_dump",
            "cli_command": "shell-environment-dump",
            "dependencies": [],
        },
        {
            "name": "Working Directory Reporter",
            "category": "Shell & Command Tools",
            "description": "Working Directory Reporter: working-directory-reporter operation.",
            "handler": "operations.working_directory_reporter",
            "cli_command": "working-directory-reporter",
            "dependencies": [],
        },
        {
            "name": "Command Timeout Runner",
            "category": "Shell & Command Tools",
            "description": "Command Timeout Runner: command-timeout-runner operation.",
            "handler": "operations.command_timeout_runner",
            "cli_command": "command-timeout-runner",
            "dependencies": [],
        },
        {
            "name": "Batch File Generator",
            "category": "Shell & Command Tools",
            "description": "Batch File Generator: batch-file-generator operation.",
            "handler": "operations.batch_file_generator",
            "cli_command": "batch-file-generator",
            "dependencies": [],
        },
        {
            "name": "PowerShell Script Generator",
            "category": "Shell & Command Tools",
            "description": "PowerShell Script Generator: powershell-script-generator operation.",
            "handler": "operations.powershell_script_generator",
            "cli_command": "powershell-script-generator",
            "dependencies": [],
        },
        {
            "name": "Shell Quoting Helper",
            "category": "Shell & Command Tools",
            "description": "Shell Quoting Helper: shell-quoting-helper operation.",
            "handler": "operations.shell_quoting_helper",
            "cli_command": "shell-quoting-helper",
            "dependencies": [],
        },
        {
            "name": "Argument Escaper",
            "category": "Shell & Command Tools",
            "description": "Argument Escaper: argument-escaper operation.",
            "handler": "operations.argument_escaper",
            "cli_command": "argument-escaper",
            "dependencies": [],
        },
        {
            "name": "Exit Code Decoder",
            "category": "Shell & Command Tools",
            "description": "Exit Code Decoder: exit-code-decoder operation.",
            "handler": "operations.exit_code_decoder",
            "cli_command": "exit-code-decoder",
            "dependencies": [],
        },
        {
            "name": "STDOUT Capture",
            "category": "Shell & Command Tools",
            "description": "STDOUT Capture: stdout-capture operation.",
            "handler": "operations.stdout_capture",
            "cli_command": "stdout-capture",
            "dependencies": [],
        },
        {
            "name": "STDERR Capture",
            "category": "Shell & Command Tools",
            "description": "STDERR Capture: stderr-capture operation.",
            "handler": "operations.stderr_capture",
            "cli_command": "stderr-capture",
            "dependencies": [],
        },
        {
            "name": "Process Pipe Helper",
            "category": "Shell & Command Tools",
            "description": "Process Pipe Helper: process-pipe-helper operation.",
            "handler": "operations.process_pipe_helper",
            "cli_command": "process-pipe-helper",
            "dependencies": [],
        },
        {
            "name": "Command Availability Scan",
            "category": "Shell & Command Tools",
            "description": "Command Availability Scan: command-availability-scan operation.",
            "handler": "operations.command_availability_scan",
            "cli_command": "command-availability-scan",
            "dependencies": [],
        },
    ]
