"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "EXIF Date Reader",
            "category": "Media Metadata",
            "description": "EXIF Date Reader: exif-date-reader operation.",
            "handler": "operations.exif_date_reader",
            "cli_command": "exif-date-reader",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "EXIF Camera Reader",
            "category": "Media Metadata",
            "description": "EXIF Camera Reader: exif-camera-reader operation.",
            "handler": "operations.exif_camera_reader",
            "cli_command": "exif-camera-reader",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Image MIME Detector",
            "category": "Media Metadata",
            "description": "Image MIME Detector: image-mime-detector operation.",
            "handler": "operations.image_mime_detector",
            "cli_command": "image-mime-detector",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Audio MIME Detector",
            "category": "Media Metadata",
            "description": "Audio MIME Detector: audio-mime-detector operation.",
            "handler": "operations.audio_mime_detector",
            "cli_command": "audio-mime-detector",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Video MIME Detector",
            "category": "Media Metadata",
            "description": "Video MIME Detector: video-mime-detector operation.",
            "handler": "operations.video_mime_detector",
            "cli_command": "video-mime-detector",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media File Scanner",
            "category": "Media Metadata",
            "description": "Media File Scanner: media-file-scanner operation.",
            "handler": "operations.media_file_scanner",
            "cli_command": "media-file-scanner",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Size Report",
            "category": "Media Metadata",
            "description": "Media Size Report: media-size-report operation.",
            "handler": "operations.media_size_report",
            "cli_command": "media-size-report",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Duration Inventory",
            "category": "Media Metadata",
            "description": "Media Duration Inventory: media-duration-inventory operation.",
            "handler": "operations.media_duration_inventory",
            "cli_command": "media-duration-inventory",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Extension Summary",
            "category": "Media Metadata",
            "description": "Media Extension Summary: media-extension-summary operation.",
            "handler": "operations.media_extension_summary",
            "cli_command": "media-extension-summary",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Duplicate Finder",
            "category": "Media Metadata",
            "description": "Media Duplicate Finder: media-duplicate-finder operation.",
            "handler": "operations.media_duplicate_finder",
            "cli_command": "media-duplicate-finder",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Hash Inventory",
            "category": "Media Metadata",
            "description": "Media Hash Inventory: media-hash-inventory operation.",
            "handler": "operations.media_hash_inventory",
            "cli_command": "media-hash-inventory",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Folder Report",
            "category": "Media Metadata",
            "description": "Media Folder Report: media-folder-report operation.",
            "handler": "operations.media_folder_report",
            "cli_command": "media-folder-report",
            "dependencies": ["ffprobe"],
        },
    ]
