"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "EXIF Date Reader",
            "category": "Media Metadata",
            "description": "Read and print exif date.",
            "handler": "operations.exif_date_reader",
            "cli_command": "exif-date-reader",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "EXIF Camera Reader",
            "category": "Media Metadata",
            "description": "Read and print exif camera.",
            "handler": "operations.exif_camera_reader",
            "cli_command": "exif-camera-reader",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Image MIME Detector",
            "category": "Media Metadata",
            "description": "Detect and identify image mime.",
            "handler": "operations.image_mime_detector",
            "cli_command": "image-mime-detector",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Audio MIME Detector",
            "category": "Media Metadata",
            "description": "Detect and identify audio mime.",
            "handler": "operations.audio_mime_detector",
            "cli_command": "audio-mime-detector",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Video MIME Detector",
            "category": "Media Metadata",
            "description": "Detect and identify video mime.",
            "handler": "operations.video_mime_detector",
            "cli_command": "video-mime-detector",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media File Scanner",
            "category": "Media Metadata",
            "description": "Scan for media file and list hits.",
            "handler": "operations.media_file_scanner",
            "cli_command": "media-file-scanner",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Size Report",
            "category": "Media Metadata",
            "description": "Compile a readable media size report report.",
            "handler": "operations.media_size_report",
            "cli_command": "media-size-report",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Duration Inventory",
            "category": "Media Metadata",
            "description": "Enumerate an inventory of media duration inventory.",
            "handler": "operations.media_duration_inventory",
            "cli_command": "media-duration-inventory",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Extension Summary",
            "category": "Media Metadata",
            "description": "Summarize media extension summary at a glance.",
            "handler": "operations.media_extension_summary",
            "cli_command": "media-extension-summary",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Duplicate Finder",
            "category": "Media Metadata",
            "description": "Locate media duplicate on disk or in scope.",
            "handler": "operations.media_duplicate_finder",
            "cli_command": "media-duplicate-finder",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Hash Inventory",
            "category": "Media Metadata",
            "description": "Enumerate an inventory of media hash inventory.",
            "handler": "operations.media_hash_inventory",
            "cli_command": "media-hash-inventory",
            "dependencies": ["ffprobe"],
        },
        {
            "name": "Media Folder Report",
            "category": "Media Metadata",
            "description": "Compile a readable media folder report report.",
            "handler": "operations.media_folder_report",
            "cli_command": "media-folder-report",
            "dependencies": ["ffprobe"],
        },
    ]
