"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Drive Information",
            "category": "Advanced Disk Tools",
            "description": "Drive Information. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.drive_information",
            "cli_command": "drive-information",
            "dependencies": [],
        },
        {
            "name": "Volume List",
            "category": "Advanced Disk Tools",
            "description": "Volume List. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.volume_list",
            "cli_command": "volume-list",
            "dependencies": [],
        },
        {
            "name": "Partition Information",
            "category": "Advanced Disk Tools",
            "description": "Partition Information. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.partition_information",
            "cli_command": "partition-information",
            "dependencies": [],
        },
        {
            "name": "Disk Free Space",
            "category": "Advanced Disk Tools",
            "description": "Disk Free Space. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.disk_free_space",
            "cli_command": "disk-free-space",
            "dependencies": [],
        },
        {
            "name": "Disk Usage Top Files",
            "category": "Advanced Disk Tools",
            "description": "Disk Usage Top Files. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.disk_usage_top_files",
            "cli_command": "disk-usage-top-files",
            "dependencies": [],
        },
        {
            "name": "Directory Size Tree",
            "category": "Advanced Disk Tools",
            "description": "Directory Size Tree. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.directory_size_tree",
            "cli_command": "directory-size-tree",
            "dependencies": [],
        },
        {
            "name": "Sparse File Inspector",
            "category": "Advanced Disk Tools",
            "description": "Sparse File Inspector. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.sparse_file_inspector",
            "cli_command": "sparse-file-inspector",
            "dependencies": [],
        },
        {
            "name": "File Allocation Inspector",
            "category": "Advanced Disk Tools",
            "description": "File Allocation Inspector. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.file_allocation_inspector",
            "cli_command": "file-allocation-inspector",
            "dependencies": [],
        },
        {
            "name": "Disk Benchmark Reader",
            "category": "Advanced Disk Tools",
            "description": "Disk Benchmark Reader. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.disk_benchmark_reader",
            "cli_command": "disk-benchmark-reader",
            "dependencies": [],
        },
        {
            "name": "SMART Status",
            "category": "Advanced Disk Tools",
            "description": "SMART Status. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.smart_status",
            "cli_command": "smart-status",
            "dependencies": [],
        },
        {
            "name": "Mount Point Viewer",
            "category": "Advanced Disk Tools",
            "description": "Mount Point Viewer. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.mount_point_viewer",
            "cli_command": "mount-point-viewer",
            "dependencies": [],
        },
        {
            "name": "Volume Serial Reader",
            "category": "Advanced Disk Tools",
            "description": "Volume Serial Reader. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.volume_serial_reader",
            "cli_command": "volume-serial-reader",
            "dependencies": [],
        },
        {
            "name": "NTFS Alternate Stream Finder",
            "category": "Advanced Disk Tools",
            "description": "NTFS Alternate Stream Finder. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.ntfs_alternate_stream_finder",
            "cli_command": "ntfs-alternate-stream-finder",
            "dependencies": [],
        },
        {
            "name": "Large File Finder",
            "category": "Advanced Disk Tools",
            "description": "Large File Finder. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.large_file_finder",
            "cli_command": "large-file-finder",
            "dependencies": [],
        },
    ]
