"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Network Adapter List",
            "category": "Network Diagnostics",
            "description": "List network adapter entries.",
            "handler": "operations.network_adapter_list",
            "cli_command": "network-adapter-list",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Network Adapter Details",
            "category": "Network Diagnostics",
            "description": "List network adapter entries.",
            "handler": "operations.network_adapter_details",
            "cli_command": "network-adapter-details",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "IPv4 Configuration",
            "category": "Network Diagnostics",
            "description": "Show detailed network adapter details.",
            "handler": "operations.ipv4_configuration",
            "cli_command": "ipv4-configuration",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "IPv6 Configuration",
            "category": "Network Diagnostics",
            "description": "IPv4 Configuration: run the 'ipv4 configuration' operation and print structured JSON results.",
            "handler": "operations.ipv6_configuration",
            "cli_command": "ipv6-configuration",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "DNS Server List",
            "category": "Network Diagnostics",
            "description": "List dns server entries.",
            "handler": "operations.dns_server_list",
            "cli_command": "dns-server-list",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Default Gateway",
            "category": "Network Diagnostics",
            "description": "List dns server entries.",
            "handler": "operations.default_gateway",
            "cli_command": "default-gateway",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "DHCP Status",
            "category": "Network Diagnostics",
            "description": "Report current dhcp status.",
            "handler": "operations.dhcp_status",
            "cli_command": "dhcp-status",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "MAC Address Viewer",
            "category": "Network Diagnostics",
            "description": "Display the contents of mac address.",
            "handler": "operations.mac_address_viewer",
            "cli_command": "mac-address-viewer",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Connection Test",
            "category": "Network Diagnostics",
            "description": "Display the contents of mac address.",
            "handler": "operations.connection_test",
            "cli_command": "connection-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "HTTP Connectivity Test",
            "category": "Network Diagnostics",
            "description": "Test connection reachability or behavior.",
            "handler": "operations.http_connectivity_test",
            "cli_command": "http-connectivity-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "HTTPS Connectivity Test",
            "category": "Network Diagnostics",
            "description": "Test http connectivity reachability or behavior.",
            "handler": "operations.https_connectivity_test",
            "cli_command": "https-connectivity-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "DNS Connectivity Test",
            "category": "Network Diagnostics",
            "description": "Test https connectivity reachability or behavior.",
            "handler": "operations.dns_connectivity_test",
            "cli_command": "dns-connectivity-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Internet Reachability",
            "category": "Network Diagnostics",
            "description": "Test dns connectivity reachability or behavior.",
            "handler": "operations.internet_reachability",
            "cli_command": "internet-reachability",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Latency Test",
            "category": "Network Diagnostics",
            "description": "Internet Reachability: run the 'internet reachability' operation and print structured JSON results.",
            "handler": "operations.latency_test",
            "cli_command": "latency-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Packet Loss Test",
            "category": "Network Diagnostics",
            "description": "Test latency reachability or behavior.",
            "handler": "operations.packet_loss_test",
            "cli_command": "packet-loss-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Proxy Configuration",
            "category": "Network Diagnostics",
            "description": "Test packet loss reachability or behavior.",
            "handler": "operations.proxy_configuration",
            "cli_command": "proxy-configuration",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "WinHTTP Proxy Viewer",
            "category": "Network Diagnostics",
            "description": "Display the contents of winhttp proxy.",
            "handler": "operations.winhttp_proxy_viewer",
            "cli_command": "winhttp-proxy-viewer",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Network Diagnostics Bundle",
            "category": "Network Diagnostics",
            "description": "Display the contents of winhttp proxy.",
            "handler": "operations.network_diagnostics_bundle",
            "cli_command": "network-diagnostics-bundle",
            "dependencies": ["powershell", "ipconfig"],
        },
    ]
