"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Network Adapter List",
            "category": "Network Diagnostics",
            "description": "Network Adapter List: performs the network adapter list action with structured, human-readable output.",
            "handler": "operations.network_adapter_list",
            "cli_command": "network-adapter-list",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Network Adapter Details",
            "category": "Network Diagnostics",
            "description": "Network Adapter Details: performs the network adapter details action with structured, human-readable output.",
            "handler": "operations.network_adapter_details",
            "cli_command": "network-adapter-details",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "IPv4 Configuration",
            "category": "Network Diagnostics",
            "description": "IPv4 Configuration: performs the ipv4 configuration action with structured, human-readable output.",
            "handler": "operations.ipv4_configuration",
            "cli_command": "ipv4-configuration",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "IPv6 Configuration",
            "category": "Network Diagnostics",
            "description": "IPv6 Configuration: performs the ipv6 configuration action with structured, human-readable output.",
            "handler": "operations.ipv6_configuration",
            "cli_command": "ipv6-configuration",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "DNS Server List",
            "category": "Network Diagnostics",
            "description": "DNS Server List: performs the dns server list action with structured, human-readable output.",
            "handler": "operations.dns_server_list",
            "cli_command": "dns-server-list",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Default Gateway",
            "category": "Network Diagnostics",
            "description": "Default Gateway: performs the default gateway action with structured, human-readable output.",
            "handler": "operations.default_gateway",
            "cli_command": "default-gateway",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "DHCP Status",
            "category": "Network Diagnostics",
            "description": "DHCP Status: performs the dhcp status action with structured, human-readable output.",
            "handler": "operations.dhcp_status",
            "cli_command": "dhcp-status",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "MAC Address Viewer",
            "category": "Network Diagnostics",
            "description": "MAC Address Viewer: performs the mac address viewer action with structured, human-readable output.",
            "handler": "operations.mac_address_viewer",
            "cli_command": "mac-address-viewer",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Connection Test",
            "category": "Network Diagnostics",
            "description": "Connection Test: performs the connection test action with structured, human-readable output.",
            "handler": "operations.connection_test",
            "cli_command": "connection-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "HTTP Connectivity Test",
            "category": "Network Diagnostics",
            "description": "HTTP Connectivity Test: performs the http connectivity test action with structured, human-readable output.",
            "handler": "operations.http_connectivity_test",
            "cli_command": "http-connectivity-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "HTTPS Connectivity Test",
            "category": "Network Diagnostics",
            "description": "HTTPS Connectivity Test: performs the https connectivity test action with structured, human-readable output.",
            "handler": "operations.https_connectivity_test",
            "cli_command": "https-connectivity-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "DNS Connectivity Test",
            "category": "Network Diagnostics",
            "description": "DNS Connectivity Test: performs the dns connectivity test action with structured, human-readable output.",
            "handler": "operations.dns_connectivity_test",
            "cli_command": "dns-connectivity-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Internet Reachability",
            "category": "Network Diagnostics",
            "description": "Internet Reachability: performs the internet reachability action with structured, human-readable output.",
            "handler": "operations.internet_reachability",
            "cli_command": "internet-reachability",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Latency Test",
            "category": "Network Diagnostics",
            "description": "Latency Test: performs the latency test action with structured, human-readable output.",
            "handler": "operations.latency_test",
            "cli_command": "latency-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Packet Loss Test",
            "category": "Network Diagnostics",
            "description": "Packet Loss Test: performs the packet loss test action with structured, human-readable output.",
            "handler": "operations.packet_loss_test",
            "cli_command": "packet-loss-test",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Proxy Configuration",
            "category": "Network Diagnostics",
            "description": "Proxy Configuration: performs the proxy configuration action with structured, human-readable output.",
            "handler": "operations.proxy_configuration",
            "cli_command": "proxy-configuration",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "WinHTTP Proxy Viewer",
            "category": "Network Diagnostics",
            "description": "WinHTTP Proxy Viewer: performs the winhttp proxy viewer action with structured, human-readable output.",
            "handler": "operations.winhttp_proxy_viewer",
            "cli_command": "winhttp-proxy-viewer",
            "dependencies": ["powershell", "ipconfig"],
        },
        {
            "name": "Network Diagnostics Bundle",
            "category": "Network Diagnostics",
            "description": "Network Diagnostics Bundle: performs the network diagnostics bundle action with structured, human-readable output.",
            "handler": "operations.network_diagnostics_bundle",
            "cli_command": "network-diagnostics-bundle",
            "dependencies": ["powershell", "ipconfig"],
        },
    ]
