"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Video Duration",
            "category": "Video Tools",
            "description": "Video Duration: video-duration operation.",
            "handler": "operations.video_duration",
            "cli_command": "video-duration",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Stream Inspector",
            "category": "Video Tools",
            "description": "Video Stream Inspector: video-stream-inspector operation.",
            "handler": "operations.video_stream_inspector",
            "cli_command": "video-stream-inspector",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Screenshot",
            "category": "Video Tools",
            "description": "Video Screenshot: video-screenshot operation.",
            "handler": "operations.video_screenshot",
            "cli_command": "video-screenshot",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Clip Cutter",
            "category": "Video Tools",
            "description": "Video Clip Cutter: video-clip-cutter operation.",
            "handler": "operations.video_clip_cutter",
            "cli_command": "video-clip-cutter",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Concatenator",
            "category": "Video Tools",
            "description": "Video Concatenator: video-concatenator operation.",
            "handler": "operations.video_concatenator",
            "cli_command": "video-concatenator",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video GIF Maker",
            "category": "Video Tools",
            "description": "Video GIF Maker: video-gif-maker operation.",
            "handler": "operations.video_gif_maker",
            "cli_command": "video-gif-maker",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Audio Extractor",
            "category": "Video Tools",
            "description": "Video Audio Extractor: video-audio-extractor operation.",
            "handler": "operations.video_audio_extractor",
            "cli_command": "video-audio-extractor",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Frame Rate Inspector",
            "category": "Video Tools",
            "description": "Video Frame Rate Inspector: video-frame-rate-inspector operation.",
            "handler": "operations.video_frame_rate_inspector",
            "cli_command": "video-frame-rate-inspector",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Resolution Inspector",
            "category": "Video Tools",
            "description": "Video Resolution Inspector: video-resolution-inspector operation.",
            "handler": "operations.video_resolution_inspector",
            "cli_command": "video-resolution-inspector",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Bitrate Inspector",
            "category": "Video Tools",
            "description": "Video Bitrate Inspector: video-bitrate-inspector operation.",
            "handler": "operations.video_bitrate_inspector",
            "cli_command": "video-bitrate-inspector",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Thumbnail Sheet",
            "category": "Video Tools",
            "description": "Video Thumbnail Sheet: video-thumbnail-sheet operation.",
            "handler": "operations.video_thumbnail_sheet",
            "cli_command": "video-thumbnail-sheet",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
        {
            "name": "Video Metadata Cleaner",
            "category": "Video Tools",
            "description": "Video Metadata Cleaner: video-metadata-cleaner operation.",
            "handler": "operations.video_metadata_cleaner",
            "cli_command": "video-metadata-cleaner",
            "dependencies": ["ffprobe", "ffmpeg"],
        },
    ]
