def register_tools():
    return [
        {
            "name": "Smart Sorter",
            "category": "File Operations",
            "description": "Organize files by extension, modification month, or size class.",
            "handler": "sorter.run",
            "cli_command": "sorter",
            "dependencies": [],
        },
        {
            "name": "Batch Renamer",
            "category": "File Operations",
            "description": "Rename files with {name}, {ext}, {counter}, and {date} placeholders.",
            "handler": "renamer.run",
            "cli_command": "renamer",
            "dependencies": [],
        },
        {
            "name": "Duplicate Finder",
            "category": "File Operations",
            "description": "Find duplicate files using size pre-filtering and content hashes.",
            "handler": "duplicate_finder.run",
            "cli_command": "dupefinder",
            "dependencies": [],
        },
        {
            "name": "File Splitter",
            "category": "File Operations",
            "description": "Split large files into numbered binary parts.",
            "handler": "splitter.run",
            "cli_command": "splitter",
            "dependencies": [],
        },
        {
            "name": "File Joiner",
            "category": "File Operations",
            "description": "Join numbered file parts back into one binary file.",
            "handler": "joiner.run",
            "cli_command": "joiner",
            "dependencies": [],
        },
        {
            "name": "Checksum Tool",
            "category": "File Operations",
            "description": "Generate or verify cryptographic checksums.",
            "handler": "checksum.run",
            "cli_command": "checksum",
            "dependencies": [],
        },
        {
            "name": "Secure Delete",
            "category": "File Operations",
            "description": "Overwrite and delete files, optionally using Sysinternals SDelete.",
            "handler": "secure_delete.run",
            "cli_command": "sdelete",
            "dependencies": [],
        },
        {
            "name": "File Age Actions",
            "category": "File Operations",
            "description": "Move, copy, or delete files older than a selected age threshold.",
            "handler": "age_actions.run",
            "cli_command": "ageactions",
            "dependencies": [],
        },
    ]
