def register_tools():
    return [
        {
            "name": "Smart Sorter",
            "category": "File Operations",
            "description": "Smart Sorter: smart sorter as structured JSON output.",
            "handler": "sorter.run",
            "cli_command": "sorter",
            "dependencies": [],
        },
        {
            "name": "Batch Renamer",
            "category": "File Operations",
            "description": "Batch Renamer: batch renamer as structured JSON output.",
            "handler": "renamer.run",
            "cli_command": "renamer",
            "dependencies": [],
        },
        {
            "name": "Duplicate Finder",
            "category": "File Operations",
            "description": "Duplicate Finder: duplicate finder as structured JSON output.",
            "handler": "duplicate_finder.run",
            "cli_command": "dupefinder",
            "dependencies": [],
        },
        {
            "name": "File Splitter",
            "category": "File Operations",
            "description": "File Splitter: file splitter as structured JSON output.",
            "handler": "splitter.run",
            "cli_command": "splitter",
            "dependencies": [],
        },
        {
            "name": "File Joiner",
            "category": "File Operations",
            "description": "File Joiner: file joiner as structured JSON output.",
            "handler": "joiner.run",
            "cli_command": "joiner",
            "dependencies": [],
        },
        {
            "name": "Checksum Tool",
            "category": "File Operations",
            "description": "Checksum Tool: checksum tool as structured JSON output.",
            "handler": "checksum.run",
            "cli_command": "checksum",
            "dependencies": [],
        },
        {
            "name": "Secure Delete",
            "category": "File Operations",
            "description": "Secure Delete: secure delete as structured JSON output.",
            "handler": "secure_delete.run",
            "cli_command": "sdelete",
            "dependencies": [],
        },
        {
            "name": "File Age Actions",
            "category": "File Operations",
            "description": "File Age Actions: file age actions as structured JSON output.",
            "handler": "age_actions.run",
            "cli_command": "ageactions",
            "dependencies": [],
        },
    ]
