"""Curated per-tool descriptions keyed by cli_command.

Generated once by scripts/write_descriptions.py; edit entries freely to
improve wording, then re-run generate_catalogs.py and audit.py.
"""
DESCRIPTIONS = {
    "administrator-group-inventory": "Enumerate an inventory of administrator group inventory.",
    "always-on-top-toggle": "Toggle always on top state on/off.",
    "angle-converter": "Convert angle between units or formats.",
    "area-converter": "Convert area between units or formats.",
    "argument-escaper": "Escape argument strings for safe shell use.",
    "arp-table-viewer": "Display the contents of arp table.",
    "audio-concatenator": "Audio Concatenator: run the \"audio concatenator\" operation and print structured JSON results.",
    "audio-device-inventory": "Enumerate an inventory of audio device inventory.",
    "audio-duration": "Audio Duration: run the \"audio duration\" operation and print structured JSON results.",
    "audio-format-converter": "Convert audio format between units or formats.",
    "audio-metadata-cleaner": "Clean up audio metadata.",
    "audio-metadata-reader": "Read and print audio metadata.",
    "audio-mime-detector": "Detect and identify audio mime.",
    "audio-normalizer": "Normalize audio to a canonical form.",
    "audio-silence-detector": "Detect and identify audio silence.",
    "audio-stream-inspector": "Inspect audio stream and report internals.",
    "audio-trim": "Audio Trim: run the \"audio trim\" operation and print structured JSON results.",
    "audio-waveform-exporter": "Export audio waveform to a file.",
    "automation-manifest": "Automation Manifest: run the \"automation manifest\" operation and print structured JSON results.",
    "autostart-diff": "Autostart Registry Diff: show differences between two inputs.",
    "b64-file": "Base64 File Codec: run the \"base64 file codec\" operation and print structured JSON results.",
    "backup-cleanup": "Backup Cleanup: run the \"backup cleanup\" operation and print structured JSON results.",
    "backup-compression": "Backup Compression: run the \"backup compression\" operation and print structured JSON results.",
    "backup-difference": "Compute the difference between backup inputs.",
    "backup-integrity-hash": "Backup Integrity Hash: run the \"backup integrity hash\" operation and print structured JSON results.",
    "backup-log-analyzer": "Analyze backup log and summarize findings.",
    "backup-manifest": "Backup Manifest: run the \"backup manifest\" operation and print structured JSON results.",
    "backup-restore": "Restore previously backed-up backup data.",
    "backup-rotation": "Backup Rotation: run the \"backup rotation\" operation and print structured JSON results.",
    "backup-schedule-generator": "Generate backup schedule output.",
    "backup-size-calculator": "Compute backup size values.",
    "backup-verify": "Backup Verify: run the \"backup verify\" operation and print structured JSON results.",
    "base64-decoder": "Decode base64.",
    "base64-encoder": "Encode base64.",
    "batch-file-generator": "Generate batch file output.",
    "battery-status": "Report current battery status.",
    "blank-line-cleaner": "Clean up blank line.",
    "bluetooth-device-inventory": "Enumerate an inventory of bluetooth device inventory.",
    "bom-handler": "BOM Handler: handle bom input and return processed results.",
    "boot-time": "Compute boot time values.",
    "broken-link-finder": "Locate broken link on disk or in scope.",
    "business-day-difference": "Compute the difference between business day inputs.",
    "bytes-converter": "Convert bytes between units or formats.",
    "calendar-month": "Calendar Month: run the \"calendar month\" operation and print structured JSON results.",
    "calendar-year": "Calendar Year: run the \"calendar year\" operation and print structured JSON results.",
    "camel-case-converter": "Convert camel case between units or formats.",
    "case-converter": "Convert case between units or formats.",
    "character-frequency": "Character Frequency: run the \"character frequency\" operation and print structured JSON results.",
    "charset-detect": "Detect and identify charset.",
    "checksum-verify": "Verify checksum integrity.",
    "clipboard-append": "Clipboard Append: run the \"clipboard append\" operation and print structured JSON results.",
    "clipboard-clear": "Clipboard Clear: run the \"clipboard clear\" operation and print structured JSON results.",
    "clipboard-hash": "Clipboard Hash: run the \"clipboard hash\" operation and print structured JSON results.",
    "clipboard-history-ring": "Maintain a rolling ring buffer of clipboard history.",
    "clipboard-line-count": "Produce a clipboard line count count.",
    "clipboard-load": "Clipboard Load: run the \"clipboard load\" operation and print structured JSON results.",
    "clipboard-normalize": "Clipboard Normalize: run the \"clipboard normalize\" operation and print structured JSON results.",
    "clipboard-paste-plain": "Clipboard Paste As Plain: run the \"clipboard paste as plain\" operation and print structured JSON results.",
    "clipboard-read": "Clipboard Read: run the \"clipboard read\" operation and print structured JSON results.",
    "clipboard-save": "Clipboard Save: run the \"clipboard save\" operation and print structured JSON results.",
    "clipboard-text-length": "Clipboard Text Length: run the \"clipboard text length\" operation and print structured JSON results.",
    "clipboard-word-count": "Produce a clipboard word count count.",
    "clipboard-write": "Clipboard Write: run the \"clipboard write\" operation and print structured JSON results.",
    "command-availability-scan": "Command Availability Scan: run the \"command availability scan\" operation and print structured JSON results.",
    "command-history-guide": "Show guidance for command history.",
    "command-resolver": "Resolve command names to concrete targets.",
    "command-timeout-runner": "Run command timeout commands and capture output.",
    "computer-name": "Computer Name: run the \"computer name\" operation and print structured JSON results.",
    "connection-test": "Test connection reachability or behavior.",
    "countdown": "Countdown: run the \"countdown\" operation and print structured JSON results.",
    "cpu-information": "CPU Information: run the \"cpu information\" operation and print structured JSON results.",
    "cpu-monitor-snapshot": "Take a point-in-time snapshot of cpu monitor snapshot.",
    "cpu-threshold-check": "Check cpu threshold and report pass/fail status.",
    "crash-dump-inventory": "Enumerate an inventory of crash dump inventory.",
    "credential-filename-finder": "Locate credential filename on disk or in scope.",
    "cron-explainer": "Explain cron expression in human terms.",
    "csv-column-extractor": "Extract data from csv column.",
    "csv-column-selector": "CSV Column Selector: run the \"csv column selector\" operation and print structured JSON results.",
    "csv-deduplicator": "CSV Deduplicator: run the \"csv deduplicator\" operation and print structured JSON results.",
    "csv-inspector": "Inspect csv and report internals.",
    "csv-normalizer": "Normalize csv to a canonical form.",
    "csv-row-filter": "Filter csv row by criteria.",
    "csv-sorter": "Sort csv records.",
    "csv-statistics": "CSV Statistics: run the \"csv statistics\" operation and print structured JSON results.",
    "csv-transposer": "CSV Transposer: run the \"csv transposer\" operation and print structured JSON results.",
    "current-user": "Current User: run the \"current user\" operation and print structured JSON results.",
    "data-rate-converter": "Convert data rate between units or formats.",
    "date-difference": "Compute the difference between date inputs.",
    "date-range-expander": "Expand date range into enumerated items.",
    "day-of-year": "Day Of Year: run the \"day of year\" operation and print structured JSON results.",
    "default-gateway": "Default Gateway: run the \"default gateway\" operation and print structured JSON results.",
    "defender-status": "Report current defender status.",
    "desktop-count-reader": "Read and print desktop count.",
    "desktop-hotkey-guide": "Show guidance for desktop hotkey.",
    "desktop-launch-helper": "Assist with desktop launch tasks.",
    "desktop-process-summary": "Summarize desktop process summary at a glance.",
    "device-class-summary": "Summarize device class summary at a glance.",
    "dhcp-status": "Report current dhcp status.",
    "diff-text-files": "Diff Text Files: run the \"diff text files\" operation and print structured JSON results.",
    "directory-change-snapshot": "Take a point-in-time snapshot of directory change snapshot.",
    "directory-csv-export": "Export directory csv data to a file.",
    "directory-json-export": "Export directory json data to a file.",
    "directory-size-monitor": "Monitor directory size over time.",
    "directory-size-tree": "Directory Size Tree: run the \"directory size tree\" operation and print structured JSON results.",
    "directory-tree-export": "Export directory tree data to a file.",
    "disk-benchmark-reader": "Read and print disk benchmark.",
    "disk-cleanup-preview": "Preview the effect of disk cleanup before applying it.",
    "disk-free-space": "Disk Free Space: run the \"disk free space\" operation and print structured JSON results.",
    "disk-monitor-snapshot": "Take a point-in-time snapshot of disk monitor snapshot.",
    "disk-space-threshold-check": "Check disk space threshold and report pass/fail status.",
    "disk-usage-top-files": "Disk Usage Top Files: run the \"disk usage top files\" operation and print structured JSON results.",
    "display-inventory": "Enumerate an inventory of display inventory.",
    "dns-cache-viewer": "Display the contents of dns cache.",
    "dns-connectivity-test": "Test dns connectivity reachability or behavior.",
    "dns-lookup": "DNS Lookup: run the \"dns lookup\" operation and print structured JSON results.",
    "dns-server-list": "List dns server entries.",
    "docx-heading-extractor": "Extract data from docx heading.",
    "docx-image-inspector": "Inspect docx image and report internals.",
    "docx-metadata": "DOCX Metadata: run the \"docx metadata\" operation and print structured JSON results.",
    "docx-paragraph-counter": "Count occurrences within docx paragraph.",
    "docx-structure-inspector": "Inspect docx structure and report internals.",
    "docx-text-extractor": "Extract data from docx text.",
    "drive-information": "Drive Information: run the \"drive information\" operation and print structured JSON results.",
    "driver-class-report": "Compile a readable driver class report report.",
    "driver-details": "Show detailed driver details.",
    "driver-device-status": "Report current driver device status.",
    "driver-list": "List driver entries.",
    "driver-provider-report": "Compile a readable driver provider report report.",
    "driver-signature-check": "Check driver signature and report pass/fail status.",
    "driver-store-inventory": "Enumerate an inventory of driver store inventory.",
    "driver-update-reminder": "Driver Update Reminder: run the \"driver update reminder\" operation and print structured JSON results.",
    "driver-version-report": "Compile a readable driver version report report.",
    "duplicate-name-finder": "Locate duplicate name on disk or in scope.",
    "encoding-detector": "Detect and identify encoding.",
    "energy-converter": "Convert energy between units or formats.",
    "environment-report": "Compile a readable environment report report.",
    "environment-variable-diff": "Environment Variable Diff: show differences between two inputs.",
    "epoch-converter": "Convert epoch between units or formats.",
    "event-log-channel-inventory": "Enumerate an inventory of event log channel inventory.",
    "event-log-export": "Export event log data to a file.",
    "event-log-guide": "Show guidance for event log.",
    "event-log-keyword-filter": "Filter event log keyword by criteria.",
    "event-log-level-summary": "Summarize event log level summary at a glance.",
    "event-log-list": "List event log entries.",
    "event-log-query": "Event Log Query: run the \"event log query\" operation and print structured JSON results.",
    "event-log-recent-errors": "Event Log Recent Errors: run the \"event log recent errors\" operation and print structured JSON results.",
    "event-log-recent-warnings": "Event Log Recent Warnings: run the \"event log recent warnings\" operation and print structured JSON results.",
    "event-log-source-search": "Search event log source targets for matches.",
    "event-log-statistics": "Event Log Statistics: run the \"event log statistics\" operation and print structured JSON results.",
    "event-log-time-filter": "Filter event log time by criteria.",
    "executable-finder": "Locate executable on disk or in scope.",
    "executable-locator": "Locate executable paths on disk.",
    "executable-package-locator": "Locate executable package paths on disk.",
    "exif-camera-reader": "Read and print exif camera.",
    "exif-date-reader": "Read and print exif date.",
    "exit-code-decoder": "Decode exit code.",
    "extension-statistics": "Extension Statistics: run the \"extension statistics\" operation and print structured JSON results.",
    "file-age-histogram": "File Age Histogram: run the \"file age histogram\" operation and print structured JSON results.",
    "file-allocation-inspector": "Inspect file allocation and report internals.",
    "file-count-monitor": "Monitor file count over time.",
    "file-permission-report": "Compile a readable file permission report report.",
    "file-size-histogram": "File Size Histogram: run the \"file size histogram\" operation and print structured JSON results.",
    "firewall-status": "Report current firewall status.",
    "folder-backup": "Back up folder targets.",
    "folder-watch-snapshot": "Take a point-in-time snapshot of folder watch snapshot.",
    "frequency-converter": "Convert frequency between units or formats.",
    "habit-streak": "Count occurrences within habit streak.",
    "hash-calculator": "Compute hash values.",
    "hex-codec": "Hex Codec: run the \"hex codec\" operation and print structured JSON results.",
    "hidden-file-finder": "Locate hidden file on disk or in scope.",
    "hidden-file-report": "Compile a readable hidden file report report.",
    "hmac-calculator": "Compute hmac values.",
    "hosts-file-audit": "Audit hosts file for policy or safety issues.",
    "hosts-file-entry-checker": "Check and validate hosts file entry.",
    "hosts-file-viewer": "Display the contents of hosts file.",
    "http-connectivity-test": "Test http connectivity reachability or behavior.",
    "http-header-inspector": "Inspect http header and report internals.",
    "https-connectivity-test": "Test https connectivity reachability or behavior.",
    "image-batch-cleanup-plan": "Image Batch Cleanup Plan: run the \"image batch cleanup plan\" operation and print structured JSON results.",
    "image-batch-contact-sheet": "Image Batch Contact Sheet: run the \"image batch contact sheet\" operation and print structured JSON results.",
    "image-batch-csv-export": "Export image batch csv data to a file.",
    "image-batch-dimensions": "Image Batch Dimensions: run the \"image batch dimensions\" operation and print structured JSON results.",
    "image-batch-duplicate-report": "Compile a readable image batch duplicate report report.",
    "image-batch-extension-convert": "Image Batch Extension Convert: run the \"image batch extension convert\" operation and print structured JSON results.",
    "image-batch-folder-summary": "Summarize image batch folder summary at a glance.",
    "image-batch-hash": "Image Batch Hash: run the \"image batch hash\" operation and print structured JSON results.",
    "image-batch-inventory": "Enumerate an inventory of image batch inventory.",
    "image-batch-json-export": "Export image batch json data to a file.",
    "image-batch-metadata-report": "Compile a readable image batch metadata report report.",
    "image-batch-orientation-report": "Compile a readable image batch orientation report report.",
    "image-batch-rename-plan": "Image Batch Rename Plan: run the \"image batch rename plan\" operation and print structured JSON results.",
    "image-batch-renamer": "Rename image batch in bulk.",
    "image-batch-resize-plan": "Image Batch Resize Plan: run the \"image batch resize plan\" operation and print structured JSON results.",
    "image-border-adder": "Image Border Adder: run the \"image border adder\" operation and print structured JSON results.",
    "image-contact-sheet": "Image Contact Sheet: run the \"image contact sheet\" operation and print structured JSON results.",
    "image-converter": "Convert image between units or formats.",
    "image-cropper": "Crop image.",
    "image-flipper": "Flip image.",
    "image-metadata-cleaner": "Clean up image metadata.",
    "image-mime-detector": "Detect and identify image mime.",
    "image-montage-builder": "Image Montage Builder: run the \"image montage builder\" operation and print structured JSON results.",
    "image-optimizer": "Optimize image.",
    "image-resizer": "Resize image.",
    "image-rotator": "Rotate image.",
    "image-watermark-tool": "Image Watermark Tool: perform image watermark operations on target files or text.",
    "import-package-test": "Test import package reachability or behavior.",
    "incremental-backup": "Back up incremental targets.",
    "indentation-analyzer": "Analyze indentation and summarize findings.",
    "indentation-normalizer": "Normalize indentation to a canonical form.",
    "installed-ram-summary": "Summarize installed ram summary at a glance.",
    "installed-software-snapshot": "Take a point-in-time snapshot of installed software snapshot.",
    "internet-reachability": "Internet Reachability: run the \"internet reachability\" operation and print structured JSON results.",
    "ip-address-info": "Show ip address information.",
    "ipv4-configuration": "IPv4 Configuration: run the \"ipv4 configuration\" operation and print structured JSON results.",
    "ipv6-configuration": "IPv6 Configuration: run the \"ipv6 configuration\" operation and print structured JSON results.",
    "iso-time-formatter": "Reformat iso time to a clean layout.",
    "json-diff": "JSON Diff: show differences between two inputs.",
    "json-inspector": "Inspect json and report internals.",
    "json-key-flattener": "JSON Key Flattener: run the \"json key flattener\" operation and print structured JSON results.",
    "json-minifier": "JSON Minifier: run the \"json minifier\" operation and print structured JSON results.",
    "json-path-extractor": "Extract data from json path.",
    "json-pretty-printer": "Print formatted json pretty.",
    "json-schema-lite-validator": "Validate json schema-lite structure or content.",
    "json-schema-validate": "Validate json schema structure or content.",
    "json-unflattener": "JSON Unflattener: run the \"json unflattener\" operation and print structured JSON results.",
    "json-yaml": "Convert json yaml between units or formats.",
    "junction-finder": "Locate junction on disk or in scope.",
    "kebab-case-converter": "Convert kebab case between units or formats.",
    "large-file-finder": "Locate large file on disk or in scope.",
    "latency-test": "Test latency reachability or behavior.",
    "length-converter": "Convert length between units or formats.",
    "line-ending-detector": "Detect and identify line ending.",
    "line-number-prefixer": "Line Number Prefixer: run the \"line number prefixer\" operation and print structured JSON results.",
    "local-account-inventory": "Enumerate an inventory of local account inventory.",
    "local-listening-ports": "Local Listening Ports: run the \"local listening ports\" operation and print structured JSON results.",
    "locale-information": "Locale Information: run the \"locale information\" operation and print structured JSON results.",
    "log-directory-inventory": "Enumerate an inventory of log directory inventory.",
    "log-rotate": "Assist with log rotation tasks.",
    "logon-task-report": "Compile a readable logon task report report.",
    "long-path-finder": "Locate long path on disk or in scope.",
    "long-running-procs": "Locate long running process on disk or in scope.",
    "mac-address-viewer": "Display the contents of mac address.",
    "mac-vendor": "MAC Vendor Lookup: run the \"mac vendor lookup\" operation and print structured JSON results.",
    "machine-architecture": "Machine Architecture: run the \"machine architecture\" operation and print structured JSON results.",
    "markdown-table-formatter": "Reformat markdown table to a clean layout.",
    "mass-converter": "Convert mass between units or formats.",
    "media-duplicate-finder": "Locate media duplicate on disk or in scope.",
    "media-duration-inventory": "Enumerate an inventory of media duration inventory.",
    "media-extension-summary": "Summarize media extension summary at a glance.",
    "media-file-scanner": "Scan for media file and list hits.",
    "media-folder-report": "Compile a readable media folder report report.",
    "media-hash-inventory": "Enumerate an inventory of media hash inventory.",
    "media-size-report": "Compile a readable media size report report.",
    "meeting-time-table": "Lay out data as a meeting time table table.",
    "memory-information": "Memory Information: run the \"memory information\" operation and print structured JSON results.",
    "memory-monitor-snapshot": "Take a point-in-time snapshot of memory monitor snapshot.",
    "memory-threshold-check": "Check memory threshold and report pass/fail status.",
    "mirror-backup": "Back up mirror targets.",
    "monitor-threshold-calculator": "Compute monitor threshold values.",
    "mount-point-viewer": "Display the contents of mount point.",
    "multi-hash": "Hash multi algorithm files or text.",
    "ndjson-filter": "Filter ndjson by criteria.",
    "ndjson-inspector": "Inspect ndjson and report internals.",
    "network-adapter-details": "Show detailed network adapter details.",
    "network-adapter-list": "List network adapter entries.",
    "network-adapter-snapshot": "Take a point-in-time snapshot of network adapter snapshot.",
    "network-connection-table": "Lay out data as a network connection table table.",
    "network-diagnostics-bundle": "Network Diagnostics Bundle: run the \"network diagnostics bundle\" operation and print structured JSON results.",
    "network-monitor-snapshot": "Take a point-in-time snapshot of network monitor snapshot.",
    "network-route-viewer": "Display the contents of network route.",
    "ngram-counter": "Count occurrences within ngram.",
    "ntfs-alternate-stream-finder": "Locate ntfs alternate stream on disk or in scope.",
    "office-file-inventory": "Enumerate an inventory of office file inventory.",
    "old-file-finder": "Locate old file on disk or in scope.",
    "open-file-guide": "Show guidance for open file.",
    "open-handles": "Compile a readable open file handle report report.",
    "open-share-guide": "Show guidance for open share.",
    "os-version": "OS Version: run the \"os version\" operation and print structured JSON results.",
    "package-cache-guide": "Show guidance for package cache.",
    "packet-loss-test": "Test packet loss reachability or behavior.",
    "partition-information": "Partition Information: run the \"partition information\" operation and print structured JSON results.",
    "patch-preview": "Preview the effect of patch before applying it.",
    "path-deduplication-report": "Compile a readable path deduplication report report.",
    "path-inspector": "Inspect path and report internals.",
    "pdf-attachment-inspector": "Inspect pdf attachment and report internals.",
    "pdf-compress": "PDF Compress: run the \"pdf compress\" operation and print structured JSON results.",
    "pdf-image-extractor": "Extract data from pdf image.",
    "pdf-merge": "PDF Merge: run the \"pdf merge\" operation and print structured JSON results.",
    "pdf-metadata-cleaner": "Clean up pdf metadata.",
    "pdf-metadata-reader": "Read and print pdf metadata.",
    "pdf-page-counter": "Count occurrences within pdf page.",
    "pdf-page-extractor": "Extract data from pdf page.",
    "pdf-rotate": "Rotate pdf logs or content.",
    "pdf-split": "PDF Split: run the \"pdf split\" operation and print structured JSON results.",
    "pdf-text-search": "Search pdf text targets for matches.",
    "pdf-watermark": "PDF Watermark: run the \"pdf watermark\" operation and print structured JSON results.",
    "ping-host": "Ping Host: run the \"ping host\" operation and print structured JSON results.",
    "pip-command-guide": "Show guidance for pip command.",
    "pomodoro-timer": "Pomodoro Timer: run the \"pomodoro timer\" operation and print structured JSON results.",
    "portable-scan": "Scan for portable app suspicion and list hits.",
    "power-converter": "Convert power between units or formats.",
    "power-source-status": "Report current power source status.",
    "powershell-command-runner": "Run powershell command commands and capture output.",
    "powershell-script-generator": "Generate powershell script output.",
    "powershell-version": "PowerShell Version: run the \"powershell version\" operation and print structured JSON results.",
    "pptx-slide-counter": "Count occurrences within pptx slide.",
    "pressure-converter": "Convert pressure between units or formats.",
    "printer-inventory": "Enumerate an inventory of printer inventory.",
    "private-key-filename-finder": "Locate private key filename on disk or in scope.",
    "process-affinity-reader": "Read and print process affinity.",
    "process-affinity-setter": "Set/apply process affinity configuration.",
    "process-cpu-snapshot": "Take a point-in-time snapshot of process cpu snapshot.",
    "process-details": "Show detailed process details.",
    "process-environment-summary": "Summarize process environment summary at a glance.",
    "process-handle-summary": "Summarize process handle summary at a glance.",
    "process-list": "List process entries.",
    "process-memory-snapshot": "Take a point-in-time snapshot of process memory snapshot.",
    "process-monitor-snapshot": "Take a point-in-time snapshot of process monitor snapshot.",
    "process-path-resolver": "Resolve process path names to concrete targets.",
    "process-pipe-helper": "Assist with process pipe tasks.",
    "process-priority-reader": "Read and print process priority.",
    "process-priority-setter": "Set/apply process priority configuration.",
    "process-search": "Search process targets for matches.",
    "process-start-time": "Compute process start time values.",
    "process-terminate": "Process Terminate: run the \"process terminate\" operation and print structured JSON results.",
    "process-tree": "Process Tree: run the \"process tree\" operation and print structured JSON results.",
    "process-wait": "Process Wait: run the \"process wait\" operation and print structured JSON results.",
    "proxy-configuration": "Proxy Configuration: run the \"proxy configuration\" operation and print structured JSON results.",
    "python-environment": "Python Environment: run the \"python environment\" operation and print structured JSON results.",
    "python-import-checker": "Check and validate python import.",
    "python-package-list": "List python package entries.",
    "python-package-versions": "Python Package Versions: run the \"python package versions\" operation and print structured JSON results.",
    "python-syntax-checker": "Check and validate python syntax.",
    "read-only-finder": "Locate read only on disk or in scope.",
    "recent-docs-report": "Compile a readable recent docs privacy report report.",
    "recent-file-finder": "Locate recent file on disk or in scope.",
    "regex-replacer": "Regex Replacer: run the \"regex replacer\" operation and print structured JSON results.",
    "regex-tester": "Test connectivity/behavior of regex.",
    "registry-backup": "Back up registry targets.",
    "registry-export": "Export registry data to a file.",
    "registry-import": "Import registry data from a file.",
    "registry-key-creator": "Registry Key Creator: run the \"registry key creator\" operation and print structured JSON results.",
    "registry-key-deleter": "Registry Key Deleter: run the \"registry key deleter\" operation and print structured JSON results.",
    "registry-path-validator": "Validate registry path structure or content.",
    "registry-query": "Registry Query: run the \"registry query\" operation and print structured JSON results.",
    "registry-value-deleter": "Registry Value Deleter: run the \"registry value deleter\" operation and print structured JSON results.",
    "registry-value-enumerator": "Registry Value Enumerator: run the \"registry value enumerator\" operation and print structured JSON results.",
    "registry-value-setter": "Set/apply registry value configuration.",
    "relative-time": "Reformat relative time to a clean layout.",
    "requirements-auditor": "Audit requirements for issues.",
    "requirements-generator": "Generate requirements output.",
    "resource-log-viewer": "Display the contents of resource log.",
    "resource-snapshot": "Resource Snapshot Diff: show differences between two inputs.",
    "resource-trend-csv": "Resource Trend CSV: run the \"resource trend csv\" operation and print structured JSON results.",
    "reverse-dns": "Reverse DNS: run the \"reverse dns\" operation and print structured JSON results.",
    "route-trace": "Route Trace: run the \"route trace\" operation and print structured JSON results.",
    "scheduled-task-details": "Show detailed scheduled task details.",
    "scheduled-task-disable": "Scheduled Task Disable: run the \"scheduled task disable\" operation and print structured JSON results.",
    "scheduled-task-enable": "Scheduled Task Enable: run the \"scheduled task enable\" operation and print structured JSON results.",
    "scheduled-task-list": "List scheduled task entries.",
    "scheduled-task-run": "Scheduled Task Run: run the \"scheduled task run\" operation and print structured JSON results.",
    "seconds-converter": "Convert seconds between units or formats.",
    "security-event-summary": "Summarize security event summary at a glance.",
    "semantic-version-comparator": "Compare semantic version inputs.",
    "sensitive-filename-finder": "Locate sensitive filename on disk or in scope.",
    "sentence-counter": "Count occurrences within sentence.",
    "service-security-report": "Compile a readable service security report report.",
    "shell-command-runner": "Run shell command commands and capture output.",
    "shell-environment-dump": "Dump shell environment contents in a readable format.",
    "shell-quoting-helper": "Assist with shell quoting tasks.",
    "size-formatter": "Reformat size to a clean layout.",
    "slugify-converter": "Convert slugify between units or formats.",
    "smart-status": "Report current smart status.",
    "snake-case-converter": "Convert snake case between units or formats.",
    "snapshot-inventory": "Enumerate an inventory of snapshot inventory.",
    "sparse-file-inspector": "Inspect sparse file and report internals.",
    "speed-converter": "Convert speed between units or formats.",
    "speed-probe": "Speed Test Probe: run the \"speed test probe\" operation and print structured JSON results.",
    "sqlite-query-runner": "Run sqlite query commands and capture output.",
    "sqlite-schema-viewer": "Display the contents of sqlite schema.",
    "sqlite-table-counter": "Count occurrences within sqlite table.",
    "sqlite-vacuum-helper": "Assist with sqlite vacuum tasks.",
    "ssh-key-audit": "Audit ssh key for policy or safety issues.",
    "ssl-expiry": "Monitor ssl expiry over time.",
    "startup-entry-inventory": "Enumerate an inventory of startup entry inventory.",
    "startup-folder-cleaner": "Clean up startup folder.",
    "startup-folder-viewer": "Display the contents of startup folder.",
    "startup-report": "Compile a readable startup report report.",
    "startup-security-audit": "Audit startup security for policy or safety issues.",
    "stderr-capture": "Capture stderr streams from child processes.",
    "stdout-capture": "Capture stdout streams from child processes.",
    "stopwatch": "Stopwatch: run the \"stopwatch\" operation and print structured JSON results.",
    "storage-health-report": "Compile a readable storage health report report.",
    "subnet-calculator": "Compute subnet values.",
    "symlink-finder": "Locate symlink on disk or in scope.",
    "system-directory-report": "Compile a readable system directory report report.",
    "system-environment-export": "Export system environment data to a file.",
    "system-information-json-export": "Export system information json data to a file.",
    "system-information-text-export": "Export system information text data to a file.",
    "system-load-report": "Compile a readable system load report report.",
    "system-summary": "Summarize system summary at a glance.",
    "system-uptime": "System Uptime: run the \"system uptime\" operation and print structured JSON results.",
    "task-trigger-guide": "Show guidance for task trigger.",
    "task-xml-export": "Export task xml data to a file.",
    "tcp-port-checker": "Check and validate tcp port.",
    "temp-aging-cleaner": "Clean up temp file aging.",
    "temperature-converter": "Convert temperature between units or formats.",
    "temporary-directory-report": "Compile a readable temporary directory report report.",
    "text-deduplicator": "Text Deduplicator: run the \"text deduplicator\" operation and print structured JSON results.",
    "text-reverse": "Text Reverse: run the \"text reverse\" operation and print structured JSON results.",
    "text-sorter": "Sort text records.",
    "text-unwrap": "Text Unwrap: run the \"text unwrap\" operation and print structured JSON results.",
    "text-wrap": "Text Wrap: run the \"text wrap\" operation and print structured JSON results.",
    "time-zone-information": "Time Zone Information: run the \"time zone information\" operation and print structured JSON results.",
    "time-zone-offset": "Time Zone Offset: run the \"time zone offset\" operation and print structured JSON results.",
    "timestamp-converter": "Convert timestamp between units or formats.",
    "title-case-converter": "Convert title case between units or formats.",
    "tls-certificate-inspector": "Inspect tls certificate and report internals.",
    "toml-structure-checker": "Check and validate toml structure.",
    "trailing-space-cleaner": "Clean up trailing space.",
    "udp-port-probe": "UDP Port Probe: run the \"udp port probe\" operation and print structured JSON results.",
    "unicode-normalizer": "Normalize unicode to a canonical form.",
    "url-decoder": "Decode url.",
    "url-encoder": "Encode url.",
    "url-redirect-checker": "Check and validate url redirect.",
    "usb-device-inventory": "Enumerate an inventory of usb device inventory.",
    "user-profile-report": "Compile a readable user profile report report.",
    "utility-suite-diagnostics": "Utility Suite Diagnostics: run the \"utility suite diagnostics\" operation and print structured JSON results.",
    "uuid-generator": "Generate uuid output.",
    "venv-size": "Produce a detailed report of venv size.",
    "version-bump-helper": "Assist with version bump tasks.",
    "video-audio-extractor": "Extract data from video audio.",
    "video-bitrate-inspector": "Inspect video bitrate and report internals.",
    "video-clip-cutter": "Cut video clip segments.",
    "video-concatenator": "Video Concatenator: run the \"video concatenator\" operation and print structured JSON results.",
    "video-duration": "Video Duration: run the \"video duration\" operation and print structured JSON results.",
    "video-frame-rate-inspector": "Inspect video frame rate and report internals.",
    "video-gif-maker": "Video GIF Maker: run the \"video gif maker\" operation and print structured JSON results.",
    "video-metadata-cleaner": "Clean up video metadata.",
    "video-mime-detector": "Detect and identify video mime.",
    "video-resolution-inspector": "Inspect video resolution and report internals.",
    "video-screenshot": "Video Screenshot: run the \"video screenshot\" operation and print structured JSON results.",
    "video-stream-inspector": "Inspect video stream and report internals.",
    "video-thumbnail-sheet": "Video Thumbnail Sheet: run the \"video thumbnail sheet\" operation and print structured JSON results.",
    "virtual-desktop-list": "List virtual desktop entries.",
    "virtual-desktop-settings": "Show or change virtual desktop settings.",
    "virtual-desktop-shortcut": "Virtual Desktop Shortcut: manage/create virtual desktop shortcuts.",
    "virtual-environment-finder": "Locate virtual environment on disk or in scope.",
    "virtual-environment-report": "Compile a readable virtual environment report report.",
    "volume-converter": "Convert volume between units or formats.",
    "volume-list": "List volume entries.",
    "volume-serial-reader": "Read and print volume serial.",
    "week-number": "Week Number: run the \"week number\" operation and print structured JSON results.",
    "wheel-inspector": "Inspect wheel and report internals.",
    "whitespace-cleaner": "Clean up whitespace.",
    "whois-lookup": "WHOIS Lookup: run the \"whois lookup\" operation and print structured JSON results.",
    "window-cascade-helper": "Assist with window cascade tasks.",
    "window-desktop-mapper": "Map relationships for window desktop mapper.",
    "window-details": "Show detailed window details.",
    "window-focus-helper": "Assist with window focus tasks.",
    "window-geometry-reader": "Read and print window geometry.",
    "window-geometry-setter": "Set/apply window geometry configuration.",
    "window-hotkey-guide": "Show guidance for window hotkey.",
    "window-list": "List window entries.",
    "window-minimize-all": "Window Minimize All: run the \"window minimize all\" operation and print structured JSON results.",
    "window-process-mapping": "Report window process mapping associations.",
    "window-restore-all": "Window Restore All: run the \"window restore all\" operation and print structured JSON results.",
    "window-tile-helper": "Assist with window tile tasks.",
    "window-title-search": "Search window title targets for matches.",
    "window-transparency-guide": "Show guidance for window transparency.",
    "windows-features-snapshot": "Take a point-in-time snapshot of windows features snapshot.",
    "windows-firewall-rule-count": "Produce a windows firewall rule count count.",
    "windows-hotfix-snapshot": "Take a point-in-time snapshot of windows hotfix snapshot.",
    "windows-update-status": "Report current windows update status.",
    "windows-version-report": "Compile a readable windows version report report.",
    "winhttp-proxy-viewer": "Display the contents of winhttp proxy.",
    "word-frequency": "Word Frequency: run the \"word frequency\" operation and print structured JSON results.",
    "working-directory-reporter": "Produce a detailed report of working directory.",
    "working-hours-calculator": "Compute working hours values.",
    "world-writable-finder": "Locate world writable on disk or in scope.",
    "xlsx-cell-counter": "Count occurrences within xlsx cell.",
    "xlsx-formula-counter": "Count occurrences within xlsx formula.",
    "xlsx-metadata": "XLSX Metadata: run the \"xlsx metadata\" operation and print structured JSON results.",
    "xlsx-sheet-lister": "XLSX Sheet Lister: run the \"xlsx sheet lister\" operation and print structured JSON results.",
    "yaml-structure-checker": "Check and validate yaml structure.",
    "zero-byte-finder": "Locate zero byte on disk or in scope.",
}
