"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "DOCX Metadata",
            "category": "Office Tools",
            "description": "DOCX Metadata: docx-metadata operation.",
            "handler": "operations.docx_metadata",
            "cli_command": "docx-metadata",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "DOCX Text Extractor",
            "category": "Office Tools",
            "description": "DOCX Text Extractor: docx-text-extractor operation.",
            "handler": "operations.docx_text_extractor",
            "cli_command": "docx-text-extractor",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "DOCX Paragraph Counter",
            "category": "Office Tools",
            "description": "DOCX Paragraph Counter: docx-paragraph-counter operation.",
            "handler": "operations.docx_paragraph_counter",
            "cli_command": "docx-paragraph-counter",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "DOCX Heading Extractor",
            "category": "Office Tools",
            "description": "DOCX Heading Extractor: docx-heading-extractor operation.",
            "handler": "operations.docx_heading_extractor",
            "cli_command": "docx-heading-extractor",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "DOCX Image Inspector",
            "category": "Office Tools",
            "description": "DOCX Image Inspector: docx-image-inspector operation.",
            "handler": "operations.docx_image_inspector",
            "cli_command": "docx-image-inspector",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "DOCX Structure Inspector",
            "category": "Office Tools",
            "description": "DOCX Structure Inspector: docx-structure-inspector operation.",
            "handler": "operations.docx_structure_inspector",
            "cli_command": "docx-structure-inspector",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "XLSX Metadata",
            "category": "Office Tools",
            "description": "XLSX Metadata: xlsx-metadata operation.",
            "handler": "operations.xlsx_metadata",
            "cli_command": "xlsx-metadata",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "XLSX Sheet Lister",
            "category": "Office Tools",
            "description": "XLSX Sheet Lister: xlsx-sheet-lister operation.",
            "handler": "operations.xlsx_sheet_lister",
            "cli_command": "xlsx-sheet-lister",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "XLSX Cell Counter",
            "category": "Office Tools",
            "description": "XLSX Cell Counter: xlsx-cell-counter operation.",
            "handler": "operations.xlsx_cell_counter",
            "cli_command": "xlsx-cell-counter",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "XLSX Formula Counter",
            "category": "Office Tools",
            "description": "XLSX Formula Counter: xlsx-formula-counter operation.",
            "handler": "operations.xlsx_formula_counter",
            "cli_command": "xlsx-formula-counter",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "PPTX Slide Counter",
            "category": "Office Tools",
            "description": "PPTX Slide Counter: pptx-slide-counter operation.",
            "handler": "operations.pptx_slide_counter",
            "cli_command": "pptx-slide-counter",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
        {
            "name": "Office File Inventory",
            "category": "Office Tools",
            "description": "Office File Inventory: office-file-inventory operation.",
            "handler": "operations.office_file_inventory",
            "cli_command": "office-file-inventory",
            "dependencies": ["python-docx", "openpyxl", "python-pptx"],
        },
    ]
