"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "System Information JSON Export",
            "category": "Extended Diagnostics",
            "description": "System Information JSON Export: system-information-json-export operation.",
            "handler": "operations.system_information_json_export",
            "cli_command": "system-information-json-export",
            "dependencies": ["powershell"],
        },
        {
            "name": "System Information Text Export",
            "category": "Extended Diagnostics",
            "description": "System Information Text Export: system-information-text-export operation.",
            "handler": "operations.system_information_text_export",
            "cli_command": "system-information-text-export",
            "dependencies": ["powershell"],
        },
        {
            "name": "Installed Software Snapshot",
            "category": "Extended Diagnostics",
            "description": "Installed Software Snapshot: installed-software-snapshot operation.",
            "handler": "operations.installed_software_snapshot",
            "cli_command": "installed-software-snapshot",
            "dependencies": ["powershell"],
        },
        {
            "name": "Windows Features Snapshot",
            "category": "Extended Diagnostics",
            "description": "Windows Features Snapshot: windows-features-snapshot operation.",
            "handler": "operations.windows_features_snapshot",
            "cli_command": "windows-features-snapshot",
            "dependencies": ["powershell"],
        },
        {
            "name": "Windows Hotfix Snapshot",
            "category": "Extended Diagnostics",
            "description": "Windows Hotfix Snapshot: windows-hotfix-snapshot operation.",
            "handler": "operations.windows_hotfix_snapshot",
            "cli_command": "windows-hotfix-snapshot",
            "dependencies": ["powershell"],
        },
        {
            "name": "Device Class Summary",
            "category": "Extended Diagnostics",
            "description": "Device Class Summary: device-class-summary operation.",
            "handler": "operations.device_class_summary",
            "cli_command": "device-class-summary",
            "dependencies": ["powershell"],
        },
        {
            "name": "USB Device Inventory",
            "category": "Extended Diagnostics",
            "description": "USB Device Inventory: usb-device-inventory operation.",
            "handler": "operations.usb_device_inventory",
            "cli_command": "usb-device-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Bluetooth Device Inventory",
            "category": "Extended Diagnostics",
            "description": "Bluetooth Device Inventory: bluetooth-device-inventory operation.",
            "handler": "operations.bluetooth_device_inventory",
            "cli_command": "bluetooth-device-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Printer Inventory",
            "category": "Extended Diagnostics",
            "description": "Printer Inventory: printer-inventory operation.",
            "handler": "operations.printer_inventory",
            "cli_command": "printer-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Display Inventory",
            "category": "Extended Diagnostics",
            "description": "Display Inventory: display-inventory operation.",
            "handler": "operations.display_inventory",
            "cli_command": "display-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Audio Device Inventory",
            "category": "Extended Diagnostics",
            "description": "Audio Device Inventory: audio-device-inventory operation.",
            "handler": "operations.audio_device_inventory",
            "cli_command": "audio-device-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Environment Variable Diff",
            "category": "Extended Diagnostics",
            "description": "Environment Variable Diff: environment-variable-diff operation.",
            "handler": "operations.environment_variable_diff",
            "cli_command": "environment-variable-diff",
            "dependencies": ["powershell"],
        },
        {
            "name": "PATH Deduplication Report",
            "category": "Extended Diagnostics",
            "description": "PATH Deduplication Report: path-deduplication-report operation.",
            "handler": "operations.path_deduplication_report",
            "cli_command": "path-deduplication-report",
            "dependencies": ["powershell"],
        },
        {
            "name": "DNS Cache Viewer",
            "category": "Extended Diagnostics",
            "description": "DNS Cache Viewer: dns-cache-viewer operation.",
            "handler": "operations.dns_cache_viewer",
            "cli_command": "dns-cache-viewer",
            "dependencies": ["powershell"],
        },
        {
            "name": "Windows Firewall Rule Count",
            "category": "Extended Diagnostics",
            "description": "Windows Firewall Rule Count: windows-firewall-rule-count operation.",
            "handler": "operations.windows_firewall_rule_count",
            "cli_command": "windows-firewall-rule-count",
            "dependencies": ["powershell"],
        },
        {
            "name": "Network Connection Table",
            "category": "Extended Diagnostics",
            "description": "Network Connection Table: network-connection-table operation.",
            "handler": "operations.network_connection_table",
            "cli_command": "network-connection-table",
            "dependencies": ["powershell"],
        },
        {
            "name": "Open File Guide",
            "category": "Extended Diagnostics",
            "description": "Open File Guide: open-file-guide operation.",
            "handler": "operations.open_file_guide",
            "cli_command": "open-file-guide",
            "dependencies": ["powershell"],
        },
        {
            "name": "Crash Dump Inventory",
            "category": "Extended Diagnostics",
            "description": "Crash Dump Inventory: crash-dump-inventory operation.",
            "handler": "operations.crash_dump_inventory",
            "cli_command": "crash-dump-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Log Directory Inventory",
            "category": "Extended Diagnostics",
            "description": "Log Directory Inventory: log-directory-inventory operation.",
            "handler": "operations.log_directory_inventory",
            "cli_command": "log-directory-inventory",
            "dependencies": ["powershell"],
        },
        {
            "name": "Utility Suite Diagnostics",
            "category": "Extended Diagnostics",
            "description": "Utility Suite Diagnostics: utility-suite-diagnostics operation.",
            "handler": "operations.utility_suite_diagnostics",
            "cli_command": "utility-suite-diagnostics",
            "dependencies": ["powershell"],
        },
    ]
