"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "File Age Histogram",
            "category": "Storage Analytics",
            "description": "File Age Histogram: file-age-histogram operation.",
            "handler": "operations.file_age_histogram",
            "cli_command": "file-age-histogram",
            "dependencies": [],
        },
        {
            "name": "Extension Statistics",
            "category": "Storage Analytics",
            "description": "Extension Statistics: extension-statistics operation.",
            "handler": "operations.extension_statistics",
            "cli_command": "extension-statistics",
            "dependencies": [],
        },
        {
            "name": "Directory Tree Export",
            "category": "Storage Analytics",
            "description": "Directory Tree Export: directory-tree-export operation.",
            "handler": "operations.directory_tree_export",
            "cli_command": "directory-tree-export",
            "dependencies": [],
        },
        {
            "name": "Directory CSV Export",
            "category": "Storage Analytics",
            "description": "Directory CSV Export: directory-csv-export operation.",
            "handler": "operations.directory_csv_export",
            "cli_command": "directory-csv-export",
            "dependencies": [],
        },
        {
            "name": "Directory JSON Export",
            "category": "Storage Analytics",
            "description": "Directory JSON Export: directory-json-export operation.",
            "handler": "operations.directory_json_export",
            "cli_command": "directory-json-export",
            "dependencies": [],
        },
        {
            "name": "Duplicate Name Finder",
            "category": "Storage Analytics",
            "description": "Duplicate Name Finder: duplicate-name-finder operation.",
            "handler": "operations.duplicate_name_finder",
            "cli_command": "duplicate-name-finder",
            "dependencies": [],
        },
        {
            "name": "Zero Byte Finder",
            "category": "Storage Analytics",
            "description": "Zero Byte Finder: zero-byte-finder operation.",
            "handler": "operations.zero_byte_finder",
            "cli_command": "zero-byte-finder",
            "dependencies": [],
        },
        {
            "name": "Read Only Finder",
            "category": "Storage Analytics",
            "description": "Read Only Finder: read-only-finder operation.",
            "handler": "operations.read_only_finder",
            "cli_command": "read-only-finder",
            "dependencies": [],
        },
        {
            "name": "Hidden File Report",
            "category": "Storage Analytics",
            "description": "Hidden File Report: hidden-file-report operation.",
            "handler": "operations.hidden_file_report",
            "cli_command": "hidden-file-report",
            "dependencies": [],
        },
        {
            "name": "Symlink Finder",
            "category": "Storage Analytics",
            "description": "Symlink Finder: symlink-finder operation.",
            "handler": "operations.symlink_finder",
            "cli_command": "symlink-finder",
            "dependencies": [],
        },
        {
            "name": "Junction Finder",
            "category": "Storage Analytics",
            "description": "Junction Finder: junction-finder operation.",
            "handler": "operations.junction_finder",
            "cli_command": "junction-finder",
            "dependencies": [],
        },
        {
            "name": "Long Path Finder",
            "category": "Storage Analytics",
            "description": "Long Path Finder: long-path-finder operation.",
            "handler": "operations.long_path_finder",
            "cli_command": "long-path-finder",
            "dependencies": [],
        },
        {
            "name": "Old File Finder",
            "category": "Storage Analytics",
            "description": "Old File Finder: old-file-finder operation.",
            "handler": "operations.old_file_finder",
            "cli_command": "old-file-finder",
            "dependencies": [],
        },
        {
            "name": "Recent File Finder",
            "category": "Storage Analytics",
            "description": "Recent File Finder: recent-file-finder operation.",
            "handler": "operations.recent_file_finder",
            "cli_command": "recent-file-finder",
            "dependencies": [],
        },
        {
            "name": "File Size Histogram",
            "category": "Storage Analytics",
            "description": "File Size Histogram: file-size-histogram operation.",
            "handler": "operations.file_size_histogram",
            "cli_command": "file-size-histogram",
            "dependencies": [],
        },
        {
            "name": "Storage Health Report",
            "category": "Storage Analytics",
            "description": "Storage Health Report: storage-health-report operation.",
            "handler": "operations.storage_health_report",
            "cli_command": "storage-health-report",
            "dependencies": [],
        },
    ]
