"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Folder Backup",
            "category": "Backup & Restore",
            "description": "Back up folder targets.",
            "handler": "operations.folder_backup",
            "cli_command": "folder-backup",
            "dependencies": [],
        },
        {
            "name": "Incremental Backup",
            "category": "Backup & Restore",
            "description": "Back up folder targets.",
            "handler": "operations.incremental_backup",
            "cli_command": "incremental-backup",
            "dependencies": [],
        },
        {
            "name": "Mirror Backup",
            "category": "Backup & Restore",
            "description": "Back up incremental targets.",
            "handler": "operations.mirror_backup",
            "cli_command": "mirror-backup",
            "dependencies": [],
        },
        {
            "name": "Backup Verify",
            "category": "Backup & Restore",
            "description": "Back up mirror targets.",
            "handler": "operations.backup_verify",
            "cli_command": "backup-verify",
            "dependencies": [],
        },
        {
            "name": "Backup Manifest",
            "category": "Backup & Restore",
            "description": "Backup Verify: run the 'backup verify' operation and print structured JSON results.",
            "handler": "operations.backup_manifest",
            "cli_command": "backup-manifest",
            "dependencies": [],
        },
        {
            "name": "Backup Difference",
            "category": "Backup & Restore",
            "description": "Backup Manifest: run the 'backup manifest' operation and print structured JSON results.",
            "handler": "operations.backup_difference",
            "cli_command": "backup-difference",
            "dependencies": [],
        },
        {
            "name": "Backup Restore",
            "category": "Backup & Restore",
            "description": "Compute the difference between backup inputs.",
            "handler": "operations.backup_restore",
            "cli_command": "backup-restore",
            "dependencies": [],
        },
        {
            "name": "Backup Cleanup",
            "category": "Backup & Restore",
            "description": "Restore previously backed-up backup data.",
            "handler": "operations.backup_cleanup",
            "cli_command": "backup-cleanup",
            "dependencies": [],
        },
        {
            "name": "Backup Rotation",
            "category": "Backup & Restore",
            "description": "Backup Cleanup: run the 'backup cleanup' operation and print structured JSON results.",
            "handler": "operations.backup_rotation",
            "cli_command": "backup-rotation",
            "dependencies": [],
        },
        {
            "name": "Backup Compression",
            "category": "Backup & Restore",
            "description": "Backup Rotation: run the 'backup rotation' operation and print structured JSON results.",
            "handler": "operations.backup_compression",
            "cli_command": "backup-compression",
            "dependencies": [],
        },
        {
            "name": "Backup Schedule Generator",
            "category": "Backup & Restore",
            "description": "Generate backup schedule output.",
            "handler": "operations.backup_schedule_generator",
            "cli_command": "backup-schedule-generator",
            "dependencies": [],
        },
        {
            "name": "Backup Size Calculator",
            "category": "Backup & Restore",
            "description": "Compute backup size values.",
            "handler": "operations.backup_size_calculator",
            "cli_command": "backup-size-calculator",
            "dependencies": [],
        },
        {
            "name": "Snapshot Inventory",
            "category": "Backup & Restore",
            "description": "Enumerate an inventory of snapshot inventory.",
            "handler": "operations.snapshot_inventory",
            "cli_command": "snapshot-inventory",
            "dependencies": [],
        },
        {
            "name": "Backup Log Analyzer",
            "category": "Backup & Restore",
            "description": "Analyze backup log and summarize findings.",
            "handler": "operations.backup_log_analyzer",
            "cli_command": "backup-log-analyzer",
            "dependencies": [],
        },
        {
            "name": "Backup Integrity Hash",
            "category": "Backup & Restore",
            "description": "Analyze backup log and summarize findings.",
            "handler": "operations.backup_integrity_hash",
            "cli_command": "backup-integrity-hash",
            "dependencies": [],
        },
    ]
