"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Folder Backup",
            "category": "Backup & Restore",
            "description": "Folder Backup: query and display folder backup details as structured JSON.",
            "handler": "operations.folder_backup",
            "cli_command": "folder-backup",
            "dependencies": [],
        },
        {
            "name": "Incremental Backup",
            "category": "Backup & Restore",
            "description": "Incremental Backup: query and display incremental backup details as structured JSON.",
            "handler": "operations.incremental_backup",
            "cli_command": "incremental-backup",
            "dependencies": [],
        },
        {
            "name": "Mirror Backup",
            "category": "Backup & Restore",
            "description": "Mirror Backup: query and display mirror backup details as structured JSON.",
            "handler": "operations.mirror_backup",
            "cli_command": "mirror-backup",
            "dependencies": [],
        },
        {
            "name": "Backup Verify",
            "category": "Backup & Restore",
            "description": "Backup Verify: query and display backup verify details as structured JSON.",
            "handler": "operations.backup_verify",
            "cli_command": "backup-verify",
            "dependencies": [],
        },
        {
            "name": "Backup Manifest",
            "category": "Backup & Restore",
            "description": "Backup Manifest: query and display backup manifest details as structured JSON.",
            "handler": "operations.backup_manifest",
            "cli_command": "backup-manifest",
            "dependencies": [],
        },
        {
            "name": "Backup Difference",
            "category": "Backup & Restore",
            "description": "Backup Difference: query and display backup difference details as structured JSON.",
            "handler": "operations.backup_difference",
            "cli_command": "backup-difference",
            "dependencies": [],
        },
        {
            "name": "Backup Restore",
            "category": "Backup & Restore",
            "description": "Backup Restore: query and display backup restore details as structured JSON.",
            "handler": "operations.backup_restore",
            "cli_command": "backup-restore",
            "dependencies": [],
        },
        {
            "name": "Backup Cleanup",
            "category": "Backup & Restore",
            "description": "Backup Cleanup: query and display backup cleanup details as structured JSON.",
            "handler": "operations.backup_cleanup",
            "cli_command": "backup-cleanup",
            "dependencies": [],
        },
        {
            "name": "Backup Rotation",
            "category": "Backup & Restore",
            "description": "Backup Rotation: query and display backup rotation details as structured JSON.",
            "handler": "operations.backup_rotation",
            "cli_command": "backup-rotation",
            "dependencies": [],
        },
        {
            "name": "Backup Compression",
            "category": "Backup & Restore",
            "description": "Backup Compression: query and display backup compression details as structured JSON.",
            "handler": "operations.backup_compression",
            "cli_command": "backup-compression",
            "dependencies": [],
        },
        {
            "name": "Backup Schedule Generator",
            "category": "Backup & Restore",
            "description": "Generate backup schedule output.",
            "handler": "operations.backup_schedule_generator",
            "cli_command": "backup-schedule-generator",
            "dependencies": [],
        },
        {
            "name": "Backup Size Calculator",
            "category": "Backup & Restore",
            "description": "Compute backup size values.",
            "handler": "operations.backup_size_calculator",
            "cli_command": "backup-size-calculator",
            "dependencies": [],
        },
        {
            "name": "Snapshot Inventory",
            "category": "Backup & Restore",
            "description": "Enumerate an inventory of snapshot inventory.",
            "handler": "operations.snapshot_inventory",
            "cli_command": "snapshot-inventory",
            "dependencies": [],
        },
        {
            "name": "Backup Log Analyzer",
            "category": "Backup & Restore",
            "description": "Analyze backup log and summarize findings.",
            "handler": "operations.backup_log_analyzer",
            "cli_command": "backup-log-analyzer",
            "dependencies": [],
        },
        {
            "name": "Backup Integrity Hash",
            "category": "Backup & Restore",
            "description": "Backup Integrity Hash: query and display backup integrity hash details as structured JSON.",
            "handler": "operations.backup_integrity_hash",
            "cli_command": "backup-integrity-hash",
            "dependencies": [],
        },
    ]
