"""Auto-generated expansion plugin pack. All handlers are lazy and delegate to core operations."""


def register_tools():
    return [
        {
            "name": "Folder Backup",
            "category": "Backup & Restore",
            "description": "Folder Backup. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.folder_backup",
            "cli_command": "folder-backup",
            "dependencies": [],
        },
        {
            "name": "Incremental Backup",
            "category": "Backup & Restore",
            "description": "Incremental Backup. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.incremental_backup",
            "cli_command": "incremental-backup",
            "dependencies": [],
        },
        {
            "name": "Mirror Backup",
            "category": "Backup & Restore",
            "description": "Mirror Backup. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.mirror_backup",
            "cli_command": "mirror-backup",
            "dependencies": [],
        },
        {
            "name": "Backup Verify",
            "category": "Backup & Restore",
            "description": "Backup Verify. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_verify",
            "cli_command": "backup-verify",
            "dependencies": [],
        },
        {
            "name": "Backup Manifest",
            "category": "Backup & Restore",
            "description": "Backup Manifest. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_manifest",
            "cli_command": "backup-manifest",
            "dependencies": [],
        },
        {
            "name": "Backup Difference",
            "category": "Backup & Restore",
            "description": "Backup Difference. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_difference",
            "cli_command": "backup-difference",
            "dependencies": [],
        },
        {
            "name": "Backup Restore",
            "category": "Backup & Restore",
            "description": "Backup Restore. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_restore",
            "cli_command": "backup-restore",
            "dependencies": [],
        },
        {
            "name": "Backup Cleanup",
            "category": "Backup & Restore",
            "description": "Backup Cleanup. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_cleanup",
            "cli_command": "backup-cleanup",
            "dependencies": [],
        },
        {
            "name": "Backup Rotation",
            "category": "Backup & Restore",
            "description": "Backup Rotation. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_rotation",
            "cli_command": "backup-rotation",
            "dependencies": [],
        },
        {
            "name": "Backup Compression",
            "category": "Backup & Restore",
            "description": "Backup Compression. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_compression",
            "cli_command": "backup-compression",
            "dependencies": [],
        },
        {
            "name": "Backup Schedule Generator",
            "category": "Backup & Restore",
            "description": "Backup Schedule Generator. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_schedule_generator",
            "cli_command": "backup-schedule-generator",
            "dependencies": [],
        },
        {
            "name": "Backup Size Calculator",
            "category": "Backup & Restore",
            "description": "Backup Size Calculator. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_size_calculator",
            "cli_command": "backup-size-calculator",
            "dependencies": [],
        },
        {
            "name": "Snapshot Inventory",
            "category": "Backup & Restore",
            "description": "Snapshot Inventory. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.snapshot_inventory",
            "cli_command": "snapshot-inventory",
            "dependencies": [],
        },
        {
            "name": "Backup Log Analyzer",
            "category": "Backup & Restore",
            "description": "Backup Log Analyzer. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_log_analyzer",
            "cli_command": "backup-log-analyzer",
            "dependencies": [],
        },
        {
            "name": "Backup Integrity Hash",
            "category": "Backup & Restore",
            "description": "Backup Integrity Hash. Uses safe, dependency-aware execution with clear diagnostics.",
            "handler": "operations.backup_integrity_hash",
            "cli_command": "backup-integrity-hash",
            "dependencies": [],
        },
    ]
